/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class AccountingInfo implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 5);

	private byte[] code = null;
	private TaxationList taxation = null;
	private DiscountingList discounting = null;
	private LocalCurrency localCurrency = null;
	private TapCurrency tapCurrency = null;
	private CurrencyConversionList currencyConversionInfo = null;
	private TapDecimalPlaces tapDecimalPlaces = null;
	
	public AccountingInfo() {
	}

	public AccountingInfo(byte[] code) {
		this.code = code;
	}

	public void setTaxation(TaxationList taxation) {
		this.taxation = taxation;
	}

	public TaxationList getTaxation() {
		return taxation;
	}

	public void setDiscounting(DiscountingList discounting) {
		this.discounting = discounting;
	}

	public DiscountingList getDiscounting() {
		return discounting;
	}

	public void setLocalCurrency(LocalCurrency localCurrency) {
		this.localCurrency = localCurrency;
	}

	public LocalCurrency getLocalCurrency() {
		return localCurrency;
	}

	public void setTapCurrency(TapCurrency tapCurrency) {
		this.tapCurrency = tapCurrency;
	}

	public TapCurrency getTapCurrency() {
		return tapCurrency;
	}

	public void setCurrencyConversionInfo(CurrencyConversionList currencyConversionInfo) {
		this.currencyConversionInfo = currencyConversionInfo;
	}

	public CurrencyConversionList getCurrencyConversionInfo() {
		return currencyConversionInfo;
	}

	public void setTapDecimalPlaces(TapDecimalPlaces tapDecimalPlaces) {
		this.tapDecimalPlaces = tapDecimalPlaces;
	}

	public TapDecimalPlaces getTapDecimalPlaces() {
		return tapDecimalPlaces;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (tapDecimalPlaces != null) {
			codeLength += tapDecimalPlaces.encode(reverseOS, true);
		}
		
		if (currencyConversionInfo != null) {
			codeLength += currencyConversionInfo.encode(reverseOS, true);
		}
		
		if (tapCurrency != null) {
			codeLength += tapCurrency.encode(reverseOS, true);
		}
		
		if (localCurrency != null) {
			codeLength += localCurrency.encode(reverseOS, true);
		}
		
		if (discounting != null) {
			codeLength += discounting.encode(reverseOS, true);
		}
		
		if (taxation != null) {
			codeLength += taxation.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(TaxationList.tag)) {
			taxation = new TaxationList();
			vByteCount += taxation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(DiscountingList.tag)) {
			discounting = new DiscountingList();
			vByteCount += discounting.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(LocalCurrency.tag)) {
			localCurrency = new LocalCurrency();
			vByteCount += localCurrency.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TapCurrency.tag)) {
			tapCurrency = new TapCurrency();
			vByteCount += tapCurrency.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(CurrencyConversionList.tag)) {
			currencyConversionInfo = new CurrencyConversionList();
			vByteCount += currencyConversionInfo.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TapDecimalPlaces.tag)) {
			tapDecimalPlaces = new TapDecimalPlaces();
			vByteCount += tapDecimalPlaces.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (taxation != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("taxation: ");
			taxation.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (discounting != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("discounting: ");
			discounting.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (localCurrency != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("localCurrency: ").append(localCurrency);
			firstSelectedElement = false;
		}
		
		if (tapCurrency != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("tapCurrency: ").append(tapCurrency);
			firstSelectedElement = false;
		}
		
		if (currencyConversionInfo != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("currencyConversionInfo: ");
			currencyConversionInfo.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (tapDecimalPlaces != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("tapDecimalPlaces: ").append(tapDecimalPlaces);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

