/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class AdvisedChargeInformation implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 351);

	private byte[] code = null;
	private PaidIndicator paidIndicator = null;
	private PaymentMethod paymentMethod = null;
	private AdvisedChargeCurrency advisedChargeCurrency = null;
	private AdvisedCharge advisedCharge = null;
	private Commission commission = null;
	
	public AdvisedChargeInformation() {
	}

	public AdvisedChargeInformation(byte[] code) {
		this.code = code;
	}

	public void setPaidIndicator(PaidIndicator paidIndicator) {
		this.paidIndicator = paidIndicator;
	}

	public PaidIndicator getPaidIndicator() {
		return paidIndicator;
	}

	public void setPaymentMethod(PaymentMethod paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	public PaymentMethod getPaymentMethod() {
		return paymentMethod;
	}

	public void setAdvisedChargeCurrency(AdvisedChargeCurrency advisedChargeCurrency) {
		this.advisedChargeCurrency = advisedChargeCurrency;
	}

	public AdvisedChargeCurrency getAdvisedChargeCurrency() {
		return advisedChargeCurrency;
	}

	public void setAdvisedCharge(AdvisedCharge advisedCharge) {
		this.advisedCharge = advisedCharge;
	}

	public AdvisedCharge getAdvisedCharge() {
		return advisedCharge;
	}

	public void setCommission(Commission commission) {
		this.commission = commission;
	}

	public Commission getCommission() {
		return commission;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (commission != null) {
			codeLength += commission.encode(reverseOS, true);
		}
		
		if (advisedCharge != null) {
			codeLength += advisedCharge.encode(reverseOS, true);
		}
		
		if (advisedChargeCurrency != null) {
			codeLength += advisedChargeCurrency.encode(reverseOS, true);
		}
		
		if (paymentMethod != null) {
			codeLength += paymentMethod.encode(reverseOS, true);
		}
		
		if (paidIndicator != null) {
			codeLength += paidIndicator.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(PaidIndicator.tag)) {
			paidIndicator = new PaidIndicator();
			vByteCount += paidIndicator.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(PaymentMethod.tag)) {
			paymentMethod = new PaymentMethod();
			vByteCount += paymentMethod.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(AdvisedChargeCurrency.tag)) {
			advisedChargeCurrency = new AdvisedChargeCurrency();
			vByteCount += advisedChargeCurrency.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(AdvisedCharge.tag)) {
			advisedCharge = new AdvisedCharge();
			vByteCount += advisedCharge.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(Commission.tag)) {
			commission = new Commission();
			vByteCount += commission.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (paidIndicator != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("paidIndicator: ").append(paidIndicator);
			firstSelectedElement = false;
		}
		
		if (paymentMethod != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("paymentMethod: ").append(paymentMethod);
			firstSelectedElement = false;
		}
		
		if (advisedChargeCurrency != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("advisedChargeCurrency: ").append(advisedChargeCurrency);
			firstSelectedElement = false;
		}
		
		if (advisedCharge != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("advisedCharge: ").append(advisedCharge);
			firstSelectedElement = false;
		}
		
		if (commission != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("commission: ").append(commission);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

