/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class AuditControlInfo implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 15);

	private byte[] code = null;
	private EarliestCallTimeStamp earliestCallTimeStamp = null;
	private LatestCallTimeStamp latestCallTimeStamp = null;
	private TotalCharge totalCharge = null;
	private TotalChargeRefund totalChargeRefund = null;
	private TotalTaxRefund totalTaxRefund = null;
	private TotalTaxValue totalTaxValue = null;
	private TotalDiscountValue totalDiscountValue = null;
	private TotalDiscountRefund totalDiscountRefund = null;
	private TotalAdvisedChargeValueList totalAdvisedChargeValueList = null;
	private CallEventDetailsCount callEventDetailsCount = null;
	private OperatorSpecInfoList operatorSpecInformation = null;
	
	public AuditControlInfo() {
	}

	public AuditControlInfo(byte[] code) {
		this.code = code;
	}

	public void setEarliestCallTimeStamp(EarliestCallTimeStamp earliestCallTimeStamp) {
		this.earliestCallTimeStamp = earliestCallTimeStamp;
	}

	public EarliestCallTimeStamp getEarliestCallTimeStamp() {
		return earliestCallTimeStamp;
	}

	public void setLatestCallTimeStamp(LatestCallTimeStamp latestCallTimeStamp) {
		this.latestCallTimeStamp = latestCallTimeStamp;
	}

	public LatestCallTimeStamp getLatestCallTimeStamp() {
		return latestCallTimeStamp;
	}

	public void setTotalCharge(TotalCharge totalCharge) {
		this.totalCharge = totalCharge;
	}

	public TotalCharge getTotalCharge() {
		return totalCharge;
	}

	public void setTotalChargeRefund(TotalChargeRefund totalChargeRefund) {
		this.totalChargeRefund = totalChargeRefund;
	}

	public TotalChargeRefund getTotalChargeRefund() {
		return totalChargeRefund;
	}

	public void setTotalTaxRefund(TotalTaxRefund totalTaxRefund) {
		this.totalTaxRefund = totalTaxRefund;
	}

	public TotalTaxRefund getTotalTaxRefund() {
		return totalTaxRefund;
	}

	public void setTotalTaxValue(TotalTaxValue totalTaxValue) {
		this.totalTaxValue = totalTaxValue;
	}

	public TotalTaxValue getTotalTaxValue() {
		return totalTaxValue;
	}

	public void setTotalDiscountValue(TotalDiscountValue totalDiscountValue) {
		this.totalDiscountValue = totalDiscountValue;
	}

	public TotalDiscountValue getTotalDiscountValue() {
		return totalDiscountValue;
	}

	public void setTotalDiscountRefund(TotalDiscountRefund totalDiscountRefund) {
		this.totalDiscountRefund = totalDiscountRefund;
	}

	public TotalDiscountRefund getTotalDiscountRefund() {
		return totalDiscountRefund;
	}

	public void setTotalAdvisedChargeValueList(TotalAdvisedChargeValueList totalAdvisedChargeValueList) {
		this.totalAdvisedChargeValueList = totalAdvisedChargeValueList;
	}

	public TotalAdvisedChargeValueList getTotalAdvisedChargeValueList() {
		return totalAdvisedChargeValueList;
	}

	public void setCallEventDetailsCount(CallEventDetailsCount callEventDetailsCount) {
		this.callEventDetailsCount = callEventDetailsCount;
	}

	public CallEventDetailsCount getCallEventDetailsCount() {
		return callEventDetailsCount;
	}

	public void setOperatorSpecInformation(OperatorSpecInfoList operatorSpecInformation) {
		this.operatorSpecInformation = operatorSpecInformation;
	}

	public OperatorSpecInfoList getOperatorSpecInformation() {
		return operatorSpecInformation;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (operatorSpecInformation != null) {
			codeLength += operatorSpecInformation.encode(reverseOS, true);
		}
		
		if (callEventDetailsCount != null) {
			codeLength += callEventDetailsCount.encode(reverseOS, true);
		}
		
		if (totalAdvisedChargeValueList != null) {
			codeLength += totalAdvisedChargeValueList.encode(reverseOS, true);
		}
		
		if (totalDiscountRefund != null) {
			codeLength += totalDiscountRefund.encode(reverseOS, true);
		}
		
		if (totalDiscountValue != null) {
			codeLength += totalDiscountValue.encode(reverseOS, true);
		}
		
		if (totalTaxValue != null) {
			codeLength += totalTaxValue.encode(reverseOS, true);
		}
		
		if (totalTaxRefund != null) {
			codeLength += totalTaxRefund.encode(reverseOS, true);
		}
		
		if (totalChargeRefund != null) {
			codeLength += totalChargeRefund.encode(reverseOS, true);
		}
		
		if (totalCharge != null) {
			codeLength += totalCharge.encode(reverseOS, true);
		}
		
		if (latestCallTimeStamp != null) {
			codeLength += latestCallTimeStamp.encode(reverseOS, true);
		}
		
		if (earliestCallTimeStamp != null) {
			codeLength += earliestCallTimeStamp.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(EarliestCallTimeStamp.tag)) {
			earliestCallTimeStamp = new EarliestCallTimeStamp();
			vByteCount += earliestCallTimeStamp.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(LatestCallTimeStamp.tag)) {
			latestCallTimeStamp = new LatestCallTimeStamp();
			vByteCount += latestCallTimeStamp.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TotalCharge.tag)) {
			totalCharge = new TotalCharge();
			vByteCount += totalCharge.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TotalChargeRefund.tag)) {
			totalChargeRefund = new TotalChargeRefund();
			vByteCount += totalChargeRefund.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TotalTaxRefund.tag)) {
			totalTaxRefund = new TotalTaxRefund();
			vByteCount += totalTaxRefund.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TotalTaxValue.tag)) {
			totalTaxValue = new TotalTaxValue();
			vByteCount += totalTaxValue.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TotalDiscountValue.tag)) {
			totalDiscountValue = new TotalDiscountValue();
			vByteCount += totalDiscountValue.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TotalDiscountRefund.tag)) {
			totalDiscountRefund = new TotalDiscountRefund();
			vByteCount += totalDiscountRefund.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TotalAdvisedChargeValueList.tag)) {
			totalAdvisedChargeValueList = new TotalAdvisedChargeValueList();
			vByteCount += totalAdvisedChargeValueList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(CallEventDetailsCount.tag)) {
			callEventDetailsCount = new CallEventDetailsCount();
			vByteCount += callEventDetailsCount.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(OperatorSpecInfoList.tag)) {
			operatorSpecInformation = new OperatorSpecInfoList();
			vByteCount += operatorSpecInformation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (earliestCallTimeStamp != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("earliestCallTimeStamp: ");
			earliestCallTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (latestCallTimeStamp != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("latestCallTimeStamp: ");
			latestCallTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (totalCharge != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalCharge: ").append(totalCharge);
			firstSelectedElement = false;
		}
		
		if (totalChargeRefund != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalChargeRefund: ").append(totalChargeRefund);
			firstSelectedElement = false;
		}
		
		if (totalTaxRefund != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalTaxRefund: ").append(totalTaxRefund);
			firstSelectedElement = false;
		}
		
		if (totalTaxValue != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalTaxValue: ").append(totalTaxValue);
			firstSelectedElement = false;
		}
		
		if (totalDiscountValue != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalDiscountValue: ").append(totalDiscountValue);
			firstSelectedElement = false;
		}
		
		if (totalDiscountRefund != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalDiscountRefund: ").append(totalDiscountRefund);
			firstSelectedElement = false;
		}
		
		if (totalAdvisedChargeValueList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalAdvisedChargeValueList: ");
			totalAdvisedChargeValueList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (callEventDetailsCount != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("callEventDetailsCount: ").append(callEventDetailsCount);
			firstSelectedElement = false;
		}
		
		if (operatorSpecInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("operatorSpecInformation: ");
			operatorSpecInformation.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

