/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class BasicServiceUsed implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 39);

	private byte[] code = null;
	private BasicService basicService = null;
	private ChargingTimeStamp chargingTimeStamp = null;
	private ChargeInformationList chargeInformationList = null;
	private HSCSDIndicator hSCSDIndicator = null;
	
	public BasicServiceUsed() {
	}

	public BasicServiceUsed(byte[] code) {
		this.code = code;
	}

	public void setBasicService(BasicService basicService) {
		this.basicService = basicService;
	}

	public BasicService getBasicService() {
		return basicService;
	}

	public void setChargingTimeStamp(ChargingTimeStamp chargingTimeStamp) {
		this.chargingTimeStamp = chargingTimeStamp;
	}

	public ChargingTimeStamp getChargingTimeStamp() {
		return chargingTimeStamp;
	}

	public void setChargeInformationList(ChargeInformationList chargeInformationList) {
		this.chargeInformationList = chargeInformationList;
	}

	public ChargeInformationList getChargeInformationList() {
		return chargeInformationList;
	}

	public void setHSCSDIndicator(HSCSDIndicator hSCSDIndicator) {
		this.hSCSDIndicator = hSCSDIndicator;
	}

	public HSCSDIndicator getHSCSDIndicator() {
		return hSCSDIndicator;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (hSCSDIndicator != null) {
			codeLength += hSCSDIndicator.encode(reverseOS, true);
		}
		
		if (chargeInformationList != null) {
			codeLength += chargeInformationList.encode(reverseOS, true);
		}
		
		if (chargingTimeStamp != null) {
			codeLength += chargingTimeStamp.encode(reverseOS, true);
		}
		
		if (basicService != null) {
			codeLength += basicService.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(BasicService.tag)) {
			basicService = new BasicService();
			vByteCount += basicService.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ChargingTimeStamp.tag)) {
			chargingTimeStamp = new ChargingTimeStamp();
			vByteCount += chargingTimeStamp.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ChargeInformationList.tag)) {
			chargeInformationList = new ChargeInformationList();
			vByteCount += chargeInformationList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(HSCSDIndicator.tag)) {
			hSCSDIndicator = new HSCSDIndicator();
			vByteCount += hSCSDIndicator.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (basicService != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("basicService: ");
			basicService.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (chargingTimeStamp != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargingTimeStamp: ");
			chargingTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (chargeInformationList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargeInformationList: ");
			chargeInformationList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (hSCSDIndicator != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("hSCSDIndicator: ").append(hSCSDIndicator);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

