/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class BatchControlInfo implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 4);

	private byte[] code = null;
	private Sender sender = null;
	private Recipient recipient = null;
	private FileSequenceNumber fileSequenceNumber = null;
	private FileCreationTimeStamp fileCreationTimeStamp = null;
	private TransferCutOffTimeStamp transferCutOffTimeStamp = null;
	private FileAvailableTimeStamp fileAvailableTimeStamp = null;
	private SpecificationVersionNumber specificationVersionNumber = null;
	private ReleaseVersionNumber releaseVersionNumber = null;
	private FileTypeIndicator fileTypeIndicator = null;
	private RapFileSequenceNumber rapFileSequenceNumber = null;
	private OperatorSpecInfoList operatorSpecInformation = null;
	
	public BatchControlInfo() {
	}

	public BatchControlInfo(byte[] code) {
		this.code = code;
	}

	public void setSender(Sender sender) {
		this.sender = sender;
	}

	public Sender getSender() {
		return sender;
	}

	public void setRecipient(Recipient recipient) {
		this.recipient = recipient;
	}

	public Recipient getRecipient() {
		return recipient;
	}

	public void setFileSequenceNumber(FileSequenceNumber fileSequenceNumber) {
		this.fileSequenceNumber = fileSequenceNumber;
	}

	public FileSequenceNumber getFileSequenceNumber() {
		return fileSequenceNumber;
	}

	public void setFileCreationTimeStamp(FileCreationTimeStamp fileCreationTimeStamp) {
		this.fileCreationTimeStamp = fileCreationTimeStamp;
	}

	public FileCreationTimeStamp getFileCreationTimeStamp() {
		return fileCreationTimeStamp;
	}

	public void setTransferCutOffTimeStamp(TransferCutOffTimeStamp transferCutOffTimeStamp) {
		this.transferCutOffTimeStamp = transferCutOffTimeStamp;
	}

	public TransferCutOffTimeStamp getTransferCutOffTimeStamp() {
		return transferCutOffTimeStamp;
	}

	public void setFileAvailableTimeStamp(FileAvailableTimeStamp fileAvailableTimeStamp) {
		this.fileAvailableTimeStamp = fileAvailableTimeStamp;
	}

	public FileAvailableTimeStamp getFileAvailableTimeStamp() {
		return fileAvailableTimeStamp;
	}

	public void setSpecificationVersionNumber(SpecificationVersionNumber specificationVersionNumber) {
		this.specificationVersionNumber = specificationVersionNumber;
	}

	public SpecificationVersionNumber getSpecificationVersionNumber() {
		return specificationVersionNumber;
	}

	public void setReleaseVersionNumber(ReleaseVersionNumber releaseVersionNumber) {
		this.releaseVersionNumber = releaseVersionNumber;
	}

	public ReleaseVersionNumber getReleaseVersionNumber() {
		return releaseVersionNumber;
	}

	public void setFileTypeIndicator(FileTypeIndicator fileTypeIndicator) {
		this.fileTypeIndicator = fileTypeIndicator;
	}

	public FileTypeIndicator getFileTypeIndicator() {
		return fileTypeIndicator;
	}

	public void setRapFileSequenceNumber(RapFileSequenceNumber rapFileSequenceNumber) {
		this.rapFileSequenceNumber = rapFileSequenceNumber;
	}

	public RapFileSequenceNumber getRapFileSequenceNumber() {
		return rapFileSequenceNumber;
	}

	public void setOperatorSpecInformation(OperatorSpecInfoList operatorSpecInformation) {
		this.operatorSpecInformation = operatorSpecInformation;
	}

	public OperatorSpecInfoList getOperatorSpecInformation() {
		return operatorSpecInformation;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (operatorSpecInformation != null) {
			codeLength += operatorSpecInformation.encode(reverseOS, true);
		}
		
		if (rapFileSequenceNumber != null) {
			codeLength += rapFileSequenceNumber.encode(reverseOS, true);
		}
		
		if (fileTypeIndicator != null) {
			codeLength += fileTypeIndicator.encode(reverseOS, true);
		}
		
		if (releaseVersionNumber != null) {
			codeLength += releaseVersionNumber.encode(reverseOS, true);
		}
		
		if (specificationVersionNumber != null) {
			codeLength += specificationVersionNumber.encode(reverseOS, true);
		}
		
		if (fileAvailableTimeStamp != null) {
			codeLength += fileAvailableTimeStamp.encode(reverseOS, true);
		}
		
		if (transferCutOffTimeStamp != null) {
			codeLength += transferCutOffTimeStamp.encode(reverseOS, true);
		}
		
		if (fileCreationTimeStamp != null) {
			codeLength += fileCreationTimeStamp.encode(reverseOS, true);
		}
		
		if (fileSequenceNumber != null) {
			codeLength += fileSequenceNumber.encode(reverseOS, true);
		}
		
		if (recipient != null) {
			codeLength += recipient.encode(reverseOS, true);
		}
		
		if (sender != null) {
			codeLength += sender.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(Sender.tag)) {
			sender = new Sender();
			vByteCount += sender.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(Recipient.tag)) {
			recipient = new Recipient();
			vByteCount += recipient.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(FileSequenceNumber.tag)) {
			fileSequenceNumber = new FileSequenceNumber();
			vByteCount += fileSequenceNumber.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(FileCreationTimeStamp.tag)) {
			fileCreationTimeStamp = new FileCreationTimeStamp();
			vByteCount += fileCreationTimeStamp.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TransferCutOffTimeStamp.tag)) {
			transferCutOffTimeStamp = new TransferCutOffTimeStamp();
			vByteCount += transferCutOffTimeStamp.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(FileAvailableTimeStamp.tag)) {
			fileAvailableTimeStamp = new FileAvailableTimeStamp();
			vByteCount += fileAvailableTimeStamp.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(SpecificationVersionNumber.tag)) {
			specificationVersionNumber = new SpecificationVersionNumber();
			vByteCount += specificationVersionNumber.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ReleaseVersionNumber.tag)) {
			releaseVersionNumber = new ReleaseVersionNumber();
			vByteCount += releaseVersionNumber.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(FileTypeIndicator.tag)) {
			fileTypeIndicator = new FileTypeIndicator();
			vByteCount += fileTypeIndicator.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(RapFileSequenceNumber.tag)) {
			rapFileSequenceNumber = new RapFileSequenceNumber();
			vByteCount += rapFileSequenceNumber.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(OperatorSpecInfoList.tag)) {
			operatorSpecInformation = new OperatorSpecInfoList();
			vByteCount += operatorSpecInformation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (sender != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("sender: ").append(sender);
			firstSelectedElement = false;
		}
		
		if (recipient != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("recipient: ").append(recipient);
			firstSelectedElement = false;
		}
		
		if (fileSequenceNumber != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("fileSequenceNumber: ").append(fileSequenceNumber);
			firstSelectedElement = false;
		}
		
		if (fileCreationTimeStamp != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("fileCreationTimeStamp: ");
			fileCreationTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (transferCutOffTimeStamp != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("transferCutOffTimeStamp: ");
			transferCutOffTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (fileAvailableTimeStamp != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("fileAvailableTimeStamp: ");
			fileAvailableTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (specificationVersionNumber != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("specificationVersionNumber: ").append(specificationVersionNumber);
			firstSelectedElement = false;
		}
		
		if (releaseVersionNumber != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("releaseVersionNumber: ").append(releaseVersionNumber);
			firstSelectedElement = false;
		}
		
		if (fileTypeIndicator != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("fileTypeIndicator: ").append(fileTypeIndicator);
			firstSelectedElement = false;
		}
		
		if (rapFileSequenceNumber != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("rapFileSequenceNumber: ").append(rapFileSequenceNumber);
			firstSelectedElement = false;
		}
		
		if (operatorSpecInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("operatorSpecInformation: ");
			operatorSpecInformation.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

