/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class CamelServiceUsed implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 57);

	private byte[] code = null;
	private CamelServiceLevel camelServiceLevel = null;
	private CamelServiceKey camelServiceKey = null;
	private DefaultCallHandlingIndicator defaultCallHandling = null;
	private ExchangeRateCode exchangeRateCode = null;
	private TaxInformationList taxInformation = null;
	private DiscountInformation discountInformation = null;
	private CamelInvocationFee camelInvocationFee = null;
	private ThreeGcamelDestination threeGcamelDestination = null;
	private CseInformation cseInformation = null;
	
	public CamelServiceUsed() {
	}

	public CamelServiceUsed(byte[] code) {
		this.code = code;
	}

	public void setCamelServiceLevel(CamelServiceLevel camelServiceLevel) {
		this.camelServiceLevel = camelServiceLevel;
	}

	public CamelServiceLevel getCamelServiceLevel() {
		return camelServiceLevel;
	}

	public void setCamelServiceKey(CamelServiceKey camelServiceKey) {
		this.camelServiceKey = camelServiceKey;
	}

	public CamelServiceKey getCamelServiceKey() {
		return camelServiceKey;
	}

	public void setDefaultCallHandling(DefaultCallHandlingIndicator defaultCallHandling) {
		this.defaultCallHandling = defaultCallHandling;
	}

	public DefaultCallHandlingIndicator getDefaultCallHandling() {
		return defaultCallHandling;
	}

	public void setExchangeRateCode(ExchangeRateCode exchangeRateCode) {
		this.exchangeRateCode = exchangeRateCode;
	}

	public ExchangeRateCode getExchangeRateCode() {
		return exchangeRateCode;
	}

	public void setTaxInformation(TaxInformationList taxInformation) {
		this.taxInformation = taxInformation;
	}

	public TaxInformationList getTaxInformation() {
		return taxInformation;
	}

	public void setDiscountInformation(DiscountInformation discountInformation) {
		this.discountInformation = discountInformation;
	}

	public DiscountInformation getDiscountInformation() {
		return discountInformation;
	}

	public void setCamelInvocationFee(CamelInvocationFee camelInvocationFee) {
		this.camelInvocationFee = camelInvocationFee;
	}

	public CamelInvocationFee getCamelInvocationFee() {
		return camelInvocationFee;
	}

	public void setThreeGcamelDestination(ThreeGcamelDestination threeGcamelDestination) {
		this.threeGcamelDestination = threeGcamelDestination;
	}

	public ThreeGcamelDestination getThreeGcamelDestination() {
		return threeGcamelDestination;
	}

	public void setCseInformation(CseInformation cseInformation) {
		this.cseInformation = cseInformation;
	}

	public CseInformation getCseInformation() {
		return cseInformation;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (cseInformation != null) {
			codeLength += cseInformation.encode(reverseOS, true);
		}
		
		if (threeGcamelDestination != null) {
			codeLength += threeGcamelDestination.encode(reverseOS, true);
		}
		
		if (camelInvocationFee != null) {
			codeLength += camelInvocationFee.encode(reverseOS, true);
		}
		
		if (discountInformation != null) {
			codeLength += discountInformation.encode(reverseOS, true);
		}
		
		if (taxInformation != null) {
			codeLength += taxInformation.encode(reverseOS, true);
		}
		
		if (exchangeRateCode != null) {
			codeLength += exchangeRateCode.encode(reverseOS, true);
		}
		
		if (defaultCallHandling != null) {
			codeLength += defaultCallHandling.encode(reverseOS, true);
		}
		
		if (camelServiceKey != null) {
			codeLength += camelServiceKey.encode(reverseOS, true);
		}
		
		if (camelServiceLevel != null) {
			codeLength += camelServiceLevel.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(CamelServiceLevel.tag)) {
			camelServiceLevel = new CamelServiceLevel();
			vByteCount += camelServiceLevel.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(CamelServiceKey.tag)) {
			camelServiceKey = new CamelServiceKey();
			vByteCount += camelServiceKey.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(DefaultCallHandlingIndicator.tag)) {
			defaultCallHandling = new DefaultCallHandlingIndicator();
			vByteCount += defaultCallHandling.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ExchangeRateCode.tag)) {
			exchangeRateCode = new ExchangeRateCode();
			vByteCount += exchangeRateCode.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TaxInformationList.tag)) {
			taxInformation = new TaxInformationList();
			vByteCount += taxInformation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(DiscountInformation.tag)) {
			discountInformation = new DiscountInformation();
			vByteCount += discountInformation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(CamelInvocationFee.tag)) {
			camelInvocationFee = new CamelInvocationFee();
			vByteCount += camelInvocationFee.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ThreeGcamelDestination.tag)) {
			threeGcamelDestination = new ThreeGcamelDestination();
			vByteCount += threeGcamelDestination.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(CseInformation.tag)) {
			cseInformation = new CseInformation();
			vByteCount += cseInformation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (camelServiceLevel != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("camelServiceLevel: ").append(camelServiceLevel);
			firstSelectedElement = false;
		}
		
		if (camelServiceKey != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("camelServiceKey: ").append(camelServiceKey);
			firstSelectedElement = false;
		}
		
		if (defaultCallHandling != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("defaultCallHandling: ").append(defaultCallHandling);
			firstSelectedElement = false;
		}
		
		if (exchangeRateCode != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("exchangeRateCode: ").append(exchangeRateCode);
			firstSelectedElement = false;
		}
		
		if (taxInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("taxInformation: ");
			taxInformation.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (discountInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("discountInformation: ");
			discountInformation.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (camelInvocationFee != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("camelInvocationFee: ").append(camelInvocationFee);
			firstSelectedElement = false;
		}
		
		if (threeGcamelDestination != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("threeGcamelDestination: ");
			threeGcamelDestination.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (cseInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("cseInformation: ").append(cseInformation);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

