/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class ChargeDetail implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 63);

	private byte[] code = null;
	private ChargeType chargeType = null;
	private Charge charge = null;
	private ChargeableUnits chargeableUnits = null;
	private ChargedUnits chargedUnits = null;
	private ChargeDetailTimeStamp chargeDetailTimeStamp = null;
	
	public ChargeDetail() {
	}

	public ChargeDetail(byte[] code) {
		this.code = code;
	}

	public void setChargeType(ChargeType chargeType) {
		this.chargeType = chargeType;
	}

	public ChargeType getChargeType() {
		return chargeType;
	}

	public void setCharge(Charge charge) {
		this.charge = charge;
	}

	public Charge getCharge() {
		return charge;
	}

	public void setChargeableUnits(ChargeableUnits chargeableUnits) {
		this.chargeableUnits = chargeableUnits;
	}

	public ChargeableUnits getChargeableUnits() {
		return chargeableUnits;
	}

	public void setChargedUnits(ChargedUnits chargedUnits) {
		this.chargedUnits = chargedUnits;
	}

	public ChargedUnits getChargedUnits() {
		return chargedUnits;
	}

	public void setChargeDetailTimeStamp(ChargeDetailTimeStamp chargeDetailTimeStamp) {
		this.chargeDetailTimeStamp = chargeDetailTimeStamp;
	}

	public ChargeDetailTimeStamp getChargeDetailTimeStamp() {
		return chargeDetailTimeStamp;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (chargeDetailTimeStamp != null) {
			codeLength += chargeDetailTimeStamp.encode(reverseOS, true);
		}
		
		if (chargedUnits != null) {
			codeLength += chargedUnits.encode(reverseOS, true);
		}
		
		if (chargeableUnits != null) {
			codeLength += chargeableUnits.encode(reverseOS, true);
		}
		
		if (charge != null) {
			codeLength += charge.encode(reverseOS, true);
		}
		
		if (chargeType != null) {
			codeLength += chargeType.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(ChargeType.tag)) {
			chargeType = new ChargeType();
			vByteCount += chargeType.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(Charge.tag)) {
			charge = new Charge();
			vByteCount += charge.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ChargeableUnits.tag)) {
			chargeableUnits = new ChargeableUnits();
			vByteCount += chargeableUnits.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ChargedUnits.tag)) {
			chargedUnits = new ChargedUnits();
			vByteCount += chargedUnits.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ChargeDetailTimeStamp.tag)) {
			chargeDetailTimeStamp = new ChargeDetailTimeStamp();
			vByteCount += chargeDetailTimeStamp.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (chargeType != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargeType: ").append(chargeType);
			firstSelectedElement = false;
		}
		
		if (charge != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("charge: ").append(charge);
			firstSelectedElement = false;
		}
		
		if (chargeableUnits != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargeableUnits: ").append(chargeableUnits);
			firstSelectedElement = false;
		}
		
		if (chargedUnits != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargedUnits: ").append(chargedUnits);
			firstSelectedElement = false;
		}
		
		if (chargeDetailTimeStamp != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargeDetailTimeStamp: ");
			chargeDetailTimeStamp.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

