/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class ChargeableSubscriber implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	private byte[] code = null;
	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 427);

	private SimChargeableSubscriber simChargeableSubscriber = null;
	private MinChargeableSubscriber minChargeableSubscriber = null;
	
	public ChargeableSubscriber() {
	}

	public ChargeableSubscriber(byte[] code) {
		this.code = code;
	}

	public void setSimChargeableSubscriber(SimChargeableSubscriber simChargeableSubscriber) {
		this.simChargeableSubscriber = simChargeableSubscriber;
	}

	public SimChargeableSubscriber getSimChargeableSubscriber() {
		return simChargeableSubscriber;
	}

	public void setMinChargeableSubscriber(MinChargeableSubscriber minChargeableSubscriber) {
		this.minChargeableSubscriber = minChargeableSubscriber;
	}

	public MinChargeableSubscriber getMinChargeableSubscriber() {
		return minChargeableSubscriber;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (minChargeableSubscriber != null) {
			codeLength += minChargeableSubscriber.encode(reverseOS, true);
			codeLength += BerLength.encodeLength(reverseOS, codeLength);
			if (withTag) {
				codeLength += tag.encode(reverseOS);
			}
			return codeLength;
		}
		
		if (simChargeableSubscriber != null) {
			codeLength += simChargeableSubscriber.encode(reverseOS, true);
			codeLength += BerLength.encodeLength(reverseOS, codeLength);
			if (withTag) {
				codeLength += tag.encode(reverseOS);
			}
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlvByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlvByteCount += tag.decodeAndCheck(is);
		}

		BerLength explicitTagLength = new BerLength();
		tlvByteCount += explicitTagLength.decode(is);
		tlvByteCount += berTag.decode(is);

		if (berTag.equals(SimChargeableSubscriber.tag)) {
			simChargeableSubscriber = new SimChargeableSubscriber();
			tlvByteCount += simChargeableSubscriber.decode(is, false);
			tlvByteCount += explicitTagLength.readEocIfIndefinite(is);
			return tlvByteCount;
		}

		if (berTag.equals(MinChargeableSubscriber.tag)) {
			minChargeableSubscriber = new MinChargeableSubscriber();
			tlvByteCount += minChargeableSubscriber.decode(is, false);
			tlvByteCount += explicitTagLength.readEocIfIndefinite(is);
			return tlvByteCount;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (simChargeableSubscriber != null) {
			sb.append("simChargeableSubscriber: ");
			simChargeableSubscriber.appendAsString(sb, indentLevel + 1);
			return;
		}

		if (minChargeableSubscriber != null) {
			sb.append("minChargeableSubscriber: ");
			minChargeableSubscriber.appendAsString(sb, indentLevel + 1);
			return;
		}

		sb.append("<none>");
	}

}

