/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class ContentTransactionBasicInfo implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 304);

	private byte[] code = null;
	private RapFileSequenceNumber rapFileSequenceNumber = null;
	private OrderPlacedTimeStamp orderPlacedTimeStamp = null;
	private RequestedDeliveryTimeStamp requestedDeliveryTimeStamp = null;
	private ActualDeliveryTimeStamp actualDeliveryTimeStamp = null;
	private TotalTransactionDuration totalTransactionDuration = null;
	private TransactionStatus transactionStatus = null;
	
	public ContentTransactionBasicInfo() {
	}

	public ContentTransactionBasicInfo(byte[] code) {
		this.code = code;
	}

	public void setRapFileSequenceNumber(RapFileSequenceNumber rapFileSequenceNumber) {
		this.rapFileSequenceNumber = rapFileSequenceNumber;
	}

	public RapFileSequenceNumber getRapFileSequenceNumber() {
		return rapFileSequenceNumber;
	}

	public void setOrderPlacedTimeStamp(OrderPlacedTimeStamp orderPlacedTimeStamp) {
		this.orderPlacedTimeStamp = orderPlacedTimeStamp;
	}

	public OrderPlacedTimeStamp getOrderPlacedTimeStamp() {
		return orderPlacedTimeStamp;
	}

	public void setRequestedDeliveryTimeStamp(RequestedDeliveryTimeStamp requestedDeliveryTimeStamp) {
		this.requestedDeliveryTimeStamp = requestedDeliveryTimeStamp;
	}

	public RequestedDeliveryTimeStamp getRequestedDeliveryTimeStamp() {
		return requestedDeliveryTimeStamp;
	}

	public void setActualDeliveryTimeStamp(ActualDeliveryTimeStamp actualDeliveryTimeStamp) {
		this.actualDeliveryTimeStamp = actualDeliveryTimeStamp;
	}

	public ActualDeliveryTimeStamp getActualDeliveryTimeStamp() {
		return actualDeliveryTimeStamp;
	}

	public void setTotalTransactionDuration(TotalTransactionDuration totalTransactionDuration) {
		this.totalTransactionDuration = totalTransactionDuration;
	}

	public TotalTransactionDuration getTotalTransactionDuration() {
		return totalTransactionDuration;
	}

	public void setTransactionStatus(TransactionStatus transactionStatus) {
		this.transactionStatus = transactionStatus;
	}

	public TransactionStatus getTransactionStatus() {
		return transactionStatus;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (transactionStatus != null) {
			codeLength += transactionStatus.encode(reverseOS, true);
		}
		
		if (totalTransactionDuration != null) {
			codeLength += totalTransactionDuration.encode(reverseOS, true);
		}
		
		if (actualDeliveryTimeStamp != null) {
			codeLength += actualDeliveryTimeStamp.encode(reverseOS, true);
		}
		
		if (requestedDeliveryTimeStamp != null) {
			codeLength += requestedDeliveryTimeStamp.encode(reverseOS, true);
		}
		
		if (orderPlacedTimeStamp != null) {
			codeLength += orderPlacedTimeStamp.encode(reverseOS, true);
		}
		
		if (rapFileSequenceNumber != null) {
			codeLength += rapFileSequenceNumber.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(RapFileSequenceNumber.tag)) {
			rapFileSequenceNumber = new RapFileSequenceNumber();
			vByteCount += rapFileSequenceNumber.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(OrderPlacedTimeStamp.tag)) {
			orderPlacedTimeStamp = new OrderPlacedTimeStamp();
			vByteCount += orderPlacedTimeStamp.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(RequestedDeliveryTimeStamp.tag)) {
			requestedDeliveryTimeStamp = new RequestedDeliveryTimeStamp();
			vByteCount += requestedDeliveryTimeStamp.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ActualDeliveryTimeStamp.tag)) {
			actualDeliveryTimeStamp = new ActualDeliveryTimeStamp();
			vByteCount += actualDeliveryTimeStamp.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TotalTransactionDuration.tag)) {
			totalTransactionDuration = new TotalTransactionDuration();
			vByteCount += totalTransactionDuration.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TransactionStatus.tag)) {
			transactionStatus = new TransactionStatus();
			vByteCount += transactionStatus.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (rapFileSequenceNumber != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("rapFileSequenceNumber: ").append(rapFileSequenceNumber);
			firstSelectedElement = false;
		}
		
		if (orderPlacedTimeStamp != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("orderPlacedTimeStamp: ");
			orderPlacedTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (requestedDeliveryTimeStamp != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("requestedDeliveryTimeStamp: ");
			requestedDeliveryTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (actualDeliveryTimeStamp != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("actualDeliveryTimeStamp: ");
			actualDeliveryTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (totalTransactionDuration != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalTransactionDuration: ").append(totalTransactionDuration);
			firstSelectedElement = false;
		}
		
		if (transactionStatus != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("transactionStatus: ").append(transactionStatus);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

