/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class LCSQosRequested implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 383);

	private byte[] code = null;
	private LCSRequestTimestamp lCSRequestTimestamp = null;
	private HorizontalAccuracyRequested horizontalAccuracyRequested = null;
	private VerticalAccuracyRequested verticalAccuracyRequested = null;
	private ResponseTimeCategory responseTimeCategory = null;
	private TrackingPeriod trackingPeriod = null;
	private TrackingFrequency trackingFrequency = null;
	
	public LCSQosRequested() {
	}

	public LCSQosRequested(byte[] code) {
		this.code = code;
	}

	public void setLCSRequestTimestamp(LCSRequestTimestamp lCSRequestTimestamp) {
		this.lCSRequestTimestamp = lCSRequestTimestamp;
	}

	public LCSRequestTimestamp getLCSRequestTimestamp() {
		return lCSRequestTimestamp;
	}

	public void setHorizontalAccuracyRequested(HorizontalAccuracyRequested horizontalAccuracyRequested) {
		this.horizontalAccuracyRequested = horizontalAccuracyRequested;
	}

	public HorizontalAccuracyRequested getHorizontalAccuracyRequested() {
		return horizontalAccuracyRequested;
	}

	public void setVerticalAccuracyRequested(VerticalAccuracyRequested verticalAccuracyRequested) {
		this.verticalAccuracyRequested = verticalAccuracyRequested;
	}

	public VerticalAccuracyRequested getVerticalAccuracyRequested() {
		return verticalAccuracyRequested;
	}

	public void setResponseTimeCategory(ResponseTimeCategory responseTimeCategory) {
		this.responseTimeCategory = responseTimeCategory;
	}

	public ResponseTimeCategory getResponseTimeCategory() {
		return responseTimeCategory;
	}

	public void setTrackingPeriod(TrackingPeriod trackingPeriod) {
		this.trackingPeriod = trackingPeriod;
	}

	public TrackingPeriod getTrackingPeriod() {
		return trackingPeriod;
	}

	public void setTrackingFrequency(TrackingFrequency trackingFrequency) {
		this.trackingFrequency = trackingFrequency;
	}

	public TrackingFrequency getTrackingFrequency() {
		return trackingFrequency;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (trackingFrequency != null) {
			codeLength += trackingFrequency.encode(reverseOS, true);
		}
		
		if (trackingPeriod != null) {
			codeLength += trackingPeriod.encode(reverseOS, true);
		}
		
		if (responseTimeCategory != null) {
			codeLength += responseTimeCategory.encode(reverseOS, true);
		}
		
		if (verticalAccuracyRequested != null) {
			codeLength += verticalAccuracyRequested.encode(reverseOS, true);
		}
		
		if (horizontalAccuracyRequested != null) {
			codeLength += horizontalAccuracyRequested.encode(reverseOS, true);
		}
		
		if (lCSRequestTimestamp != null) {
			codeLength += lCSRequestTimestamp.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(LCSRequestTimestamp.tag)) {
			lCSRequestTimestamp = new LCSRequestTimestamp();
			vByteCount += lCSRequestTimestamp.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(HorizontalAccuracyRequested.tag)) {
			horizontalAccuracyRequested = new HorizontalAccuracyRequested();
			vByteCount += horizontalAccuracyRequested.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(VerticalAccuracyRequested.tag)) {
			verticalAccuracyRequested = new VerticalAccuracyRequested();
			vByteCount += verticalAccuracyRequested.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ResponseTimeCategory.tag)) {
			responseTimeCategory = new ResponseTimeCategory();
			vByteCount += responseTimeCategory.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TrackingPeriod.tag)) {
			trackingPeriod = new TrackingPeriod();
			vByteCount += trackingPeriod.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TrackingFrequency.tag)) {
			trackingFrequency = new TrackingFrequency();
			vByteCount += trackingFrequency.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (lCSRequestTimestamp != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("lCSRequestTimestamp: ");
			lCSRequestTimestamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (horizontalAccuracyRequested != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("horizontalAccuracyRequested: ").append(horizontalAccuracyRequested);
			firstSelectedElement = false;
		}
		
		if (verticalAccuracyRequested != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("verticalAccuracyRequested: ").append(verticalAccuracyRequested);
			firstSelectedElement = false;
		}
		
		if (responseTimeCategory != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("responseTimeCategory: ").append(responseTimeCategory);
			firstSelectedElement = false;
		}
		
		if (trackingPeriod != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackingPeriod: ").append(trackingPeriod);
			firstSelectedElement = false;
		}
		
		if (trackingFrequency != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackingFrequency: ").append(trackingFrequency);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

