/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class LCSQosDelivered implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 390);

	private byte[] code = null;
	private LCSTransactionStatus lCSTransactionStatus = null;
	private HorizontalAccuracyDelivered horizontalAccuracyDelivered = null;
	private VerticalAccuracyDelivered verticalAccuracyDelivered = null;
	private ResponseTime responseTime = null;
	private PositioningMethod positioningMethod = null;
	private TrackingPeriod trackingPeriod = null;
	private TrackingFrequency trackingFrequency = null;
	private AgeOfLocation ageOfLocation = null;
	
	public LCSQosDelivered() {
	}

	public LCSQosDelivered(byte[] code) {
		this.code = code;
	}

	public void setLCSTransactionStatus(LCSTransactionStatus lCSTransactionStatus) {
		this.lCSTransactionStatus = lCSTransactionStatus;
	}

	public LCSTransactionStatus getLCSTransactionStatus() {
		return lCSTransactionStatus;
	}

	public void setHorizontalAccuracyDelivered(HorizontalAccuracyDelivered horizontalAccuracyDelivered) {
		this.horizontalAccuracyDelivered = horizontalAccuracyDelivered;
	}

	public HorizontalAccuracyDelivered getHorizontalAccuracyDelivered() {
		return horizontalAccuracyDelivered;
	}

	public void setVerticalAccuracyDelivered(VerticalAccuracyDelivered verticalAccuracyDelivered) {
		this.verticalAccuracyDelivered = verticalAccuracyDelivered;
	}

	public VerticalAccuracyDelivered getVerticalAccuracyDelivered() {
		return verticalAccuracyDelivered;
	}

	public void setResponseTime(ResponseTime responseTime) {
		this.responseTime = responseTime;
	}

	public ResponseTime getResponseTime() {
		return responseTime;
	}

	public void setPositioningMethod(PositioningMethod positioningMethod) {
		this.positioningMethod = positioningMethod;
	}

	public PositioningMethod getPositioningMethod() {
		return positioningMethod;
	}

	public void setTrackingPeriod(TrackingPeriod trackingPeriod) {
		this.trackingPeriod = trackingPeriod;
	}

	public TrackingPeriod getTrackingPeriod() {
		return trackingPeriod;
	}

	public void setTrackingFrequency(TrackingFrequency trackingFrequency) {
		this.trackingFrequency = trackingFrequency;
	}

	public TrackingFrequency getTrackingFrequency() {
		return trackingFrequency;
	}

	public void setAgeOfLocation(AgeOfLocation ageOfLocation) {
		this.ageOfLocation = ageOfLocation;
	}

	public AgeOfLocation getAgeOfLocation() {
		return ageOfLocation;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (ageOfLocation != null) {
			codeLength += ageOfLocation.encode(reverseOS, true);
		}
		
		if (trackingFrequency != null) {
			codeLength += trackingFrequency.encode(reverseOS, true);
		}
		
		if (trackingPeriod != null) {
			codeLength += trackingPeriod.encode(reverseOS, true);
		}
		
		if (positioningMethod != null) {
			codeLength += positioningMethod.encode(reverseOS, true);
		}
		
		if (responseTime != null) {
			codeLength += responseTime.encode(reverseOS, true);
		}
		
		if (verticalAccuracyDelivered != null) {
			codeLength += verticalAccuracyDelivered.encode(reverseOS, true);
		}
		
		if (horizontalAccuracyDelivered != null) {
			codeLength += horizontalAccuracyDelivered.encode(reverseOS, true);
		}
		
		if (lCSTransactionStatus != null) {
			codeLength += lCSTransactionStatus.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(LCSTransactionStatus.tag)) {
			lCSTransactionStatus = new LCSTransactionStatus();
			vByteCount += lCSTransactionStatus.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(HorizontalAccuracyDelivered.tag)) {
			horizontalAccuracyDelivered = new HorizontalAccuracyDelivered();
			vByteCount += horizontalAccuracyDelivered.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(VerticalAccuracyDelivered.tag)) {
			verticalAccuracyDelivered = new VerticalAccuracyDelivered();
			vByteCount += verticalAccuracyDelivered.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ResponseTime.tag)) {
			responseTime = new ResponseTime();
			vByteCount += responseTime.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(PositioningMethod.tag)) {
			positioningMethod = new PositioningMethod();
			vByteCount += positioningMethod.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TrackingPeriod.tag)) {
			trackingPeriod = new TrackingPeriod();
			vByteCount += trackingPeriod.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TrackingFrequency.tag)) {
			trackingFrequency = new TrackingFrequency();
			vByteCount += trackingFrequency.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(AgeOfLocation.tag)) {
			ageOfLocation = new AgeOfLocation();
			vByteCount += ageOfLocation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (lCSTransactionStatus != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("lCSTransactionStatus: ").append(lCSTransactionStatus);
			firstSelectedElement = false;
		}
		
		if (horizontalAccuracyDelivered != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("horizontalAccuracyDelivered: ").append(horizontalAccuracyDelivered);
			firstSelectedElement = false;
		}
		
		if (verticalAccuracyDelivered != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("verticalAccuracyDelivered: ").append(verticalAccuracyDelivered);
			firstSelectedElement = false;
		}
		
		if (responseTime != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("responseTime: ").append(responseTime);
			firstSelectedElement = false;
		}
		
		if (positioningMethod != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("positioningMethod: ").append(positioningMethod);
			firstSelectedElement = false;
		}
		
		if (trackingPeriod != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackingPeriod: ").append(trackingPeriod);
			firstSelectedElement = false;
		}
		
		if (trackingFrequency != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackingFrequency: ").append(trackingFrequency);
			firstSelectedElement = false;
		}
		
		if (ageOfLocation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("ageOfLocation: ").append(ageOfLocation);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

