/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class LocationService implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 297);

	private byte[] code = null;
	private RapFileSequenceNumber rapFileSequenceNumber = null;
	private RecEntityCode recEntityCode = null;
	private CallReference callReference = null;
	private TrackingCustomerInformation trackingCustomerInformation = null;
	private LCSSPInformation lCSSPInformation = null;
	private TrackedCustomerInformation trackedCustomerInformation = null;
	private LocationServiceUsage locationServiceUsage = null;
	private OperatorSpecInfoList operatorSpecInformation = null;
	
	public LocationService() {
	}

	public LocationService(byte[] code) {
		this.code = code;
	}

	public void setRapFileSequenceNumber(RapFileSequenceNumber rapFileSequenceNumber) {
		this.rapFileSequenceNumber = rapFileSequenceNumber;
	}

	public RapFileSequenceNumber getRapFileSequenceNumber() {
		return rapFileSequenceNumber;
	}

	public void setRecEntityCode(RecEntityCode recEntityCode) {
		this.recEntityCode = recEntityCode;
	}

	public RecEntityCode getRecEntityCode() {
		return recEntityCode;
	}

	public void setCallReference(CallReference callReference) {
		this.callReference = callReference;
	}

	public CallReference getCallReference() {
		return callReference;
	}

	public void setTrackingCustomerInformation(TrackingCustomerInformation trackingCustomerInformation) {
		this.trackingCustomerInformation = trackingCustomerInformation;
	}

	public TrackingCustomerInformation getTrackingCustomerInformation() {
		return trackingCustomerInformation;
	}

	public void setLCSSPInformation(LCSSPInformation lCSSPInformation) {
		this.lCSSPInformation = lCSSPInformation;
	}

	public LCSSPInformation getLCSSPInformation() {
		return lCSSPInformation;
	}

	public void setTrackedCustomerInformation(TrackedCustomerInformation trackedCustomerInformation) {
		this.trackedCustomerInformation = trackedCustomerInformation;
	}

	public TrackedCustomerInformation getTrackedCustomerInformation() {
		return trackedCustomerInformation;
	}

	public void setLocationServiceUsage(LocationServiceUsage locationServiceUsage) {
		this.locationServiceUsage = locationServiceUsage;
	}

	public LocationServiceUsage getLocationServiceUsage() {
		return locationServiceUsage;
	}

	public void setOperatorSpecInformation(OperatorSpecInfoList operatorSpecInformation) {
		this.operatorSpecInformation = operatorSpecInformation;
	}

	public OperatorSpecInfoList getOperatorSpecInformation() {
		return operatorSpecInformation;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (operatorSpecInformation != null) {
			codeLength += operatorSpecInformation.encode(reverseOS, true);
		}
		
		if (locationServiceUsage != null) {
			codeLength += locationServiceUsage.encode(reverseOS, true);
		}
		
		if (trackedCustomerInformation != null) {
			codeLength += trackedCustomerInformation.encode(reverseOS, true);
		}
		
		if (lCSSPInformation != null) {
			codeLength += lCSSPInformation.encode(reverseOS, true);
		}
		
		if (trackingCustomerInformation != null) {
			codeLength += trackingCustomerInformation.encode(reverseOS, true);
		}
		
		if (callReference != null) {
			codeLength += callReference.encode(reverseOS, true);
		}
		
		if (recEntityCode != null) {
			codeLength += recEntityCode.encode(reverseOS, true);
		}
		
		if (rapFileSequenceNumber != null) {
			codeLength += rapFileSequenceNumber.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(RapFileSequenceNumber.tag)) {
			rapFileSequenceNumber = new RapFileSequenceNumber();
			vByteCount += rapFileSequenceNumber.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(RecEntityCode.tag)) {
			recEntityCode = new RecEntityCode();
			vByteCount += recEntityCode.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(CallReference.tag)) {
			callReference = new CallReference();
			vByteCount += callReference.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TrackingCustomerInformation.tag)) {
			trackingCustomerInformation = new TrackingCustomerInformation();
			vByteCount += trackingCustomerInformation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(LCSSPInformation.tag)) {
			lCSSPInformation = new LCSSPInformation();
			vByteCount += lCSSPInformation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TrackedCustomerInformation.tag)) {
			trackedCustomerInformation = new TrackedCustomerInformation();
			vByteCount += trackedCustomerInformation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(LocationServiceUsage.tag)) {
			locationServiceUsage = new LocationServiceUsage();
			vByteCount += locationServiceUsage.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(OperatorSpecInfoList.tag)) {
			operatorSpecInformation = new OperatorSpecInfoList();
			vByteCount += operatorSpecInformation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (rapFileSequenceNumber != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("rapFileSequenceNumber: ").append(rapFileSequenceNumber);
			firstSelectedElement = false;
		}
		
		if (recEntityCode != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("recEntityCode: ").append(recEntityCode);
			firstSelectedElement = false;
		}
		
		if (callReference != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("callReference: ").append(callReference);
			firstSelectedElement = false;
		}
		
		if (trackingCustomerInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackingCustomerInformation: ");
			trackingCustomerInformation.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (lCSSPInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("lCSSPInformation: ");
			lCSSPInformation.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (trackedCustomerInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackedCustomerInformation: ");
			trackedCustomerInformation.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (locationServiceUsage != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("locationServiceUsage: ");
			locationServiceUsage.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (operatorSpecInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("operatorSpecInformation: ");
			operatorSpecInformation.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

