/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class MobileTerminatedCall implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 10);

	private byte[] code = null;
	private MtBasicCallInformation basicCallInformation = null;
	private LocationInformation locationInformation = null;
	private ImeiOrEsn equipmentIdentifier = null;
	private BasicServiceUsedList basicServiceUsedList = null;
	private CamelServiceUsed camelServiceUsed = null;
	private OperatorSpecInfoList operatorSpecInformation = null;
	
	public MobileTerminatedCall() {
	}

	public MobileTerminatedCall(byte[] code) {
		this.code = code;
	}

	public void setBasicCallInformation(MtBasicCallInformation basicCallInformation) {
		this.basicCallInformation = basicCallInformation;
	}

	public MtBasicCallInformation getBasicCallInformation() {
		return basicCallInformation;
	}

	public void setLocationInformation(LocationInformation locationInformation) {
		this.locationInformation = locationInformation;
	}

	public LocationInformation getLocationInformation() {
		return locationInformation;
	}

	public void setEquipmentIdentifier(ImeiOrEsn equipmentIdentifier) {
		this.equipmentIdentifier = equipmentIdentifier;
	}

	public ImeiOrEsn getEquipmentIdentifier() {
		return equipmentIdentifier;
	}

	public void setBasicServiceUsedList(BasicServiceUsedList basicServiceUsedList) {
		this.basicServiceUsedList = basicServiceUsedList;
	}

	public BasicServiceUsedList getBasicServiceUsedList() {
		return basicServiceUsedList;
	}

	public void setCamelServiceUsed(CamelServiceUsed camelServiceUsed) {
		this.camelServiceUsed = camelServiceUsed;
	}

	public CamelServiceUsed getCamelServiceUsed() {
		return camelServiceUsed;
	}

	public void setOperatorSpecInformation(OperatorSpecInfoList operatorSpecInformation) {
		this.operatorSpecInformation = operatorSpecInformation;
	}

	public OperatorSpecInfoList getOperatorSpecInformation() {
		return operatorSpecInformation;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (operatorSpecInformation != null) {
			codeLength += operatorSpecInformation.encode(reverseOS, true);
		}
		
		if (camelServiceUsed != null) {
			codeLength += camelServiceUsed.encode(reverseOS, true);
		}
		
		if (basicServiceUsedList != null) {
			codeLength += basicServiceUsedList.encode(reverseOS, true);
		}
		
		if (equipmentIdentifier != null) {
			codeLength += equipmentIdentifier.encode(reverseOS, true);
		}
		
		if (locationInformation != null) {
			codeLength += locationInformation.encode(reverseOS, true);
		}
		
		if (basicCallInformation != null) {
			codeLength += basicCallInformation.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(MtBasicCallInformation.tag)) {
			basicCallInformation = new MtBasicCallInformation();
			vByteCount += basicCallInformation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(LocationInformation.tag)) {
			locationInformation = new LocationInformation();
			vByteCount += locationInformation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ImeiOrEsn.tag)) {
			equipmentIdentifier = new ImeiOrEsn();
			vByteCount += equipmentIdentifier.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BasicServiceUsedList.tag)) {
			basicServiceUsedList = new BasicServiceUsedList();
			vByteCount += basicServiceUsedList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(CamelServiceUsed.tag)) {
			camelServiceUsed = new CamelServiceUsed();
			vByteCount += camelServiceUsed.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(OperatorSpecInfoList.tag)) {
			operatorSpecInformation = new OperatorSpecInfoList();
			vByteCount += operatorSpecInformation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (basicCallInformation != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("basicCallInformation: ");
			basicCallInformation.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (locationInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("locationInformation: ");
			locationInformation.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (equipmentIdentifier != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("equipmentIdentifier: ");
			equipmentIdentifier.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (basicServiceUsedList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("basicServiceUsedList: ");
			basicServiceUsedList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (camelServiceUsed != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("camelServiceUsed: ");
			camelServiceUsed.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (operatorSpecInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("operatorSpecInformation: ");
			operatorSpecInformation.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

