/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class ScuBasicInformation implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 191);

	private byte[] code = null;
	private ScuChargeableSubscriber chargeableSubscriber = null;
	private ChargedPartyStatus chargedPartyStatus = null;
	private NonChargedNumber nonChargedNumber = null;
	private ClirIndicator clirIndicator = null;
	private OriginatingNetwork originatingNetwork = null;
	private DestinationNetwork destinationNetwork = null;
	
	public ScuBasicInformation() {
	}

	public ScuBasicInformation(byte[] code) {
		this.code = code;
	}

	public void setChargeableSubscriber(ScuChargeableSubscriber chargeableSubscriber) {
		this.chargeableSubscriber = chargeableSubscriber;
	}

	public ScuChargeableSubscriber getChargeableSubscriber() {
		return chargeableSubscriber;
	}

	public void setChargedPartyStatus(ChargedPartyStatus chargedPartyStatus) {
		this.chargedPartyStatus = chargedPartyStatus;
	}

	public ChargedPartyStatus getChargedPartyStatus() {
		return chargedPartyStatus;
	}

	public void setNonChargedNumber(NonChargedNumber nonChargedNumber) {
		this.nonChargedNumber = nonChargedNumber;
	}

	public NonChargedNumber getNonChargedNumber() {
		return nonChargedNumber;
	}

	public void setClirIndicator(ClirIndicator clirIndicator) {
		this.clirIndicator = clirIndicator;
	}

	public ClirIndicator getClirIndicator() {
		return clirIndicator;
	}

	public void setOriginatingNetwork(OriginatingNetwork originatingNetwork) {
		this.originatingNetwork = originatingNetwork;
	}

	public OriginatingNetwork getOriginatingNetwork() {
		return originatingNetwork;
	}

	public void setDestinationNetwork(DestinationNetwork destinationNetwork) {
		this.destinationNetwork = destinationNetwork;
	}

	public DestinationNetwork getDestinationNetwork() {
		return destinationNetwork;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (destinationNetwork != null) {
			codeLength += destinationNetwork.encode(reverseOS, true);
		}
		
		if (originatingNetwork != null) {
			codeLength += originatingNetwork.encode(reverseOS, true);
		}
		
		if (clirIndicator != null) {
			codeLength += clirIndicator.encode(reverseOS, true);
		}
		
		if (nonChargedNumber != null) {
			codeLength += nonChargedNumber.encode(reverseOS, true);
		}
		
		if (chargedPartyStatus != null) {
			codeLength += chargedPartyStatus.encode(reverseOS, true);
		}
		
		if (chargeableSubscriber != null) {
			codeLength += chargeableSubscriber.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(ScuChargeableSubscriber.tag)) {
			chargeableSubscriber = new ScuChargeableSubscriber();
			vByteCount += chargeableSubscriber.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ChargedPartyStatus.tag)) {
			chargedPartyStatus = new ChargedPartyStatus();
			vByteCount += chargedPartyStatus.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(NonChargedNumber.tag)) {
			nonChargedNumber = new NonChargedNumber();
			vByteCount += nonChargedNumber.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ClirIndicator.tag)) {
			clirIndicator = new ClirIndicator();
			vByteCount += clirIndicator.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(OriginatingNetwork.tag)) {
			originatingNetwork = new OriginatingNetwork();
			vByteCount += originatingNetwork.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(DestinationNetwork.tag)) {
			destinationNetwork = new DestinationNetwork();
			vByteCount += destinationNetwork.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (chargeableSubscriber != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargeableSubscriber: ");
			chargeableSubscriber.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (chargedPartyStatus != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargedPartyStatus: ").append(chargedPartyStatus);
			firstSelectedElement = false;
		}
		
		if (nonChargedNumber != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("nonChargedNumber: ").append(nonChargedNumber);
			firstSelectedElement = false;
		}
		
		if (clirIndicator != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("clirIndicator: ").append(clirIndicator);
			firstSelectedElement = false;
		}
		
		if (originatingNetwork != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("originatingNetwork: ").append(originatingNetwork);
			firstSelectedElement = false;
		}
		
		if (destinationNetwork != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("destinationNetwork: ").append(destinationNetwork);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

