/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class ScuChargeType implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 192);

	private byte[] code = null;
	private MessageStatus messageStatus = null;
	private PriorityCode priorityCode = null;
	private DistanceChargeBandCode distanceChargeBandCode = null;
	private MessageType messageType = null;
	private MessageDescriptionCode messageDescriptionCode = null;
	
	public ScuChargeType() {
	}

	public ScuChargeType(byte[] code) {
		this.code = code;
	}

	public void setMessageStatus(MessageStatus messageStatus) {
		this.messageStatus = messageStatus;
	}

	public MessageStatus getMessageStatus() {
		return messageStatus;
	}

	public void setPriorityCode(PriorityCode priorityCode) {
		this.priorityCode = priorityCode;
	}

	public PriorityCode getPriorityCode() {
		return priorityCode;
	}

	public void setDistanceChargeBandCode(DistanceChargeBandCode distanceChargeBandCode) {
		this.distanceChargeBandCode = distanceChargeBandCode;
	}

	public DistanceChargeBandCode getDistanceChargeBandCode() {
		return distanceChargeBandCode;
	}

	public void setMessageType(MessageType messageType) {
		this.messageType = messageType;
	}

	public MessageType getMessageType() {
		return messageType;
	}

	public void setMessageDescriptionCode(MessageDescriptionCode messageDescriptionCode) {
		this.messageDescriptionCode = messageDescriptionCode;
	}

	public MessageDescriptionCode getMessageDescriptionCode() {
		return messageDescriptionCode;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (messageDescriptionCode != null) {
			codeLength += messageDescriptionCode.encode(reverseOS, true);
		}
		
		if (messageType != null) {
			codeLength += messageType.encode(reverseOS, true);
		}
		
		if (distanceChargeBandCode != null) {
			codeLength += distanceChargeBandCode.encode(reverseOS, true);
		}
		
		if (priorityCode != null) {
			codeLength += priorityCode.encode(reverseOS, true);
		}
		
		if (messageStatus != null) {
			codeLength += messageStatus.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(MessageStatus.tag)) {
			messageStatus = new MessageStatus();
			vByteCount += messageStatus.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(PriorityCode.tag)) {
			priorityCode = new PriorityCode();
			vByteCount += priorityCode.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(DistanceChargeBandCode.tag)) {
			distanceChargeBandCode = new DistanceChargeBandCode();
			vByteCount += distanceChargeBandCode.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(MessageType.tag)) {
			messageType = new MessageType();
			vByteCount += messageType.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(MessageDescriptionCode.tag)) {
			messageDescriptionCode = new MessageDescriptionCode();
			vByteCount += messageDescriptionCode.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (messageStatus != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("messageStatus: ").append(messageStatus);
			firstSelectedElement = false;
		}
		
		if (priorityCode != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("priorityCode: ").append(priorityCode);
			firstSelectedElement = false;
		}
		
		if (distanceChargeBandCode != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("distanceChargeBandCode: ").append(distanceChargeBandCode);
			firstSelectedElement = false;
		}
		
		if (messageType != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("messageType: ").append(messageType);
			firstSelectedElement = false;
		}
		
		if (messageDescriptionCode != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("messageDescriptionCode: ").append(messageDescriptionCode);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

