/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class ScuTimeStamps implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 193);

	private byte[] code = null;
	private DepositTimeStamp depositTimeStamp = null;
	private CompletionTimeStamp completionTimeStamp = null;
	private ChargingPoint chargingPoint = null;
	
	public ScuTimeStamps() {
	}

	public ScuTimeStamps(byte[] code) {
		this.code = code;
	}

	public void setDepositTimeStamp(DepositTimeStamp depositTimeStamp) {
		this.depositTimeStamp = depositTimeStamp;
	}

	public DepositTimeStamp getDepositTimeStamp() {
		return depositTimeStamp;
	}

	public void setCompletionTimeStamp(CompletionTimeStamp completionTimeStamp) {
		this.completionTimeStamp = completionTimeStamp;
	}

	public CompletionTimeStamp getCompletionTimeStamp() {
		return completionTimeStamp;
	}

	public void setChargingPoint(ChargingPoint chargingPoint) {
		this.chargingPoint = chargingPoint;
	}

	public ChargingPoint getChargingPoint() {
		return chargingPoint;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (chargingPoint != null) {
			codeLength += chargingPoint.encode(reverseOS, true);
		}
		
		if (completionTimeStamp != null) {
			codeLength += completionTimeStamp.encode(reverseOS, true);
		}
		
		if (depositTimeStamp != null) {
			codeLength += depositTimeStamp.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(DepositTimeStamp.tag)) {
			depositTimeStamp = new DepositTimeStamp();
			vByteCount += depositTimeStamp.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(CompletionTimeStamp.tag)) {
			completionTimeStamp = new CompletionTimeStamp();
			vByteCount += completionTimeStamp.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ChargingPoint.tag)) {
			chargingPoint = new ChargingPoint();
			vByteCount += chargingPoint.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (depositTimeStamp != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("depositTimeStamp: ");
			depositTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (completionTimeStamp != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("completionTimeStamp: ");
			completionTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (chargingPoint != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargingPoint: ").append(chargingPoint);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

