/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class ServingPartiesInformation implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 335);

	private byte[] code = null;
	private ContentProviderName contentProviderName = null;
	private ContentProviderIdList contentProviderIdList = null;
	private InternetServiceProviderIdList internetServiceProviderIdList = null;
	private NetworkList networkList = null;
	
	public ServingPartiesInformation() {
	}

	public ServingPartiesInformation(byte[] code) {
		this.code = code;
	}

	public void setContentProviderName(ContentProviderName contentProviderName) {
		this.contentProviderName = contentProviderName;
	}

	public ContentProviderName getContentProviderName() {
		return contentProviderName;
	}

	public void setContentProviderIdList(ContentProviderIdList contentProviderIdList) {
		this.contentProviderIdList = contentProviderIdList;
	}

	public ContentProviderIdList getContentProviderIdList() {
		return contentProviderIdList;
	}

	public void setInternetServiceProviderIdList(InternetServiceProviderIdList internetServiceProviderIdList) {
		this.internetServiceProviderIdList = internetServiceProviderIdList;
	}

	public InternetServiceProviderIdList getInternetServiceProviderIdList() {
		return internetServiceProviderIdList;
	}

	public void setNetworkList(NetworkList networkList) {
		this.networkList = networkList;
	}

	public NetworkList getNetworkList() {
		return networkList;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (networkList != null) {
			codeLength += networkList.encode(reverseOS, true);
		}
		
		if (internetServiceProviderIdList != null) {
			codeLength += internetServiceProviderIdList.encode(reverseOS, true);
		}
		
		if (contentProviderIdList != null) {
			codeLength += contentProviderIdList.encode(reverseOS, true);
		}
		
		if (contentProviderName != null) {
			codeLength += contentProviderName.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(ContentProviderName.tag)) {
			contentProviderName = new ContentProviderName();
			vByteCount += contentProviderName.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ContentProviderIdList.tag)) {
			contentProviderIdList = new ContentProviderIdList();
			vByteCount += contentProviderIdList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(InternetServiceProviderIdList.tag)) {
			internetServiceProviderIdList = new InternetServiceProviderIdList();
			vByteCount += internetServiceProviderIdList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(NetworkList.tag)) {
			networkList = new NetworkList();
			vByteCount += networkList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (contentProviderName != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("contentProviderName: ").append(contentProviderName);
			firstSelectedElement = false;
		}
		
		if (contentProviderIdList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("contentProviderIdList: ");
			contentProviderIdList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (internetServiceProviderIdList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("internetServiceProviderIdList: ");
			internetServiceProviderIdList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (networkList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("networkList: ");
			networkList.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

