/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class SessionChargeInformation implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 449);

	private byte[] code = null;
	private ChargedItem chargedItem = null;
	private ExchangeRateCode exchangeRateCode = null;
	private CallTypeGroup callTypeGroup = null;
	private ChargeDetailList chargeDetailList = null;
	private TaxInformationList taxInformationList = null;
	
	public SessionChargeInformation() {
	}

	public SessionChargeInformation(byte[] code) {
		this.code = code;
	}

	public void setChargedItem(ChargedItem chargedItem) {
		this.chargedItem = chargedItem;
	}

	public ChargedItem getChargedItem() {
		return chargedItem;
	}

	public void setExchangeRateCode(ExchangeRateCode exchangeRateCode) {
		this.exchangeRateCode = exchangeRateCode;
	}

	public ExchangeRateCode getExchangeRateCode() {
		return exchangeRateCode;
	}

	public void setCallTypeGroup(CallTypeGroup callTypeGroup) {
		this.callTypeGroup = callTypeGroup;
	}

	public CallTypeGroup getCallTypeGroup() {
		return callTypeGroup;
	}

	public void setChargeDetailList(ChargeDetailList chargeDetailList) {
		this.chargeDetailList = chargeDetailList;
	}

	public ChargeDetailList getChargeDetailList() {
		return chargeDetailList;
	}

	public void setTaxInformationList(TaxInformationList taxInformationList) {
		this.taxInformationList = taxInformationList;
	}

	public TaxInformationList getTaxInformationList() {
		return taxInformationList;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (taxInformationList != null) {
			codeLength += taxInformationList.encode(reverseOS, true);
		}
		
		if (chargeDetailList != null) {
			codeLength += chargeDetailList.encode(reverseOS, true);
		}
		
		if (callTypeGroup != null) {
			codeLength += callTypeGroup.encode(reverseOS, true);
		}
		
		if (exchangeRateCode != null) {
			codeLength += exchangeRateCode.encode(reverseOS, true);
		}
		
		if (chargedItem != null) {
			codeLength += chargedItem.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(ChargedItem.tag)) {
			chargedItem = new ChargedItem();
			vByteCount += chargedItem.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ExchangeRateCode.tag)) {
			exchangeRateCode = new ExchangeRateCode();
			vByteCount += exchangeRateCode.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(CallTypeGroup.tag)) {
			callTypeGroup = new CallTypeGroup();
			vByteCount += callTypeGroup.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ChargeDetailList.tag)) {
			chargeDetailList = new ChargeDetailList();
			vByteCount += chargeDetailList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TaxInformationList.tag)) {
			taxInformationList = new TaxInformationList();
			vByteCount += taxInformationList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (chargedItem != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargedItem: ").append(chargedItem);
			firstSelectedElement = false;
		}
		
		if (exchangeRateCode != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("exchangeRateCode: ").append(exchangeRateCode);
			firstSelectedElement = false;
		}
		
		if (callTypeGroup != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("callTypeGroup: ");
			callTypeGroup.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (chargeDetailList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargeDetailList: ");
			chargeDetailList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (taxInformationList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("taxInformationList: ");
			taxInformationList.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

