/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class SupplServiceUsed implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 206);

	private byte[] code = null;
	private SupplServiceCode supplServiceCode = null;
	private SupplServiceActionCode supplServiceActionCode = null;
	private SsParameters ssParameters = null;
	private ChargingTimeStamp chargingTimeStamp = null;
	private ChargeInformation chargeInformation = null;
	private BasicServiceCodeList basicServiceCodeList = null;
	
	public SupplServiceUsed() {
	}

	public SupplServiceUsed(byte[] code) {
		this.code = code;
	}

	public void setSupplServiceCode(SupplServiceCode supplServiceCode) {
		this.supplServiceCode = supplServiceCode;
	}

	public SupplServiceCode getSupplServiceCode() {
		return supplServiceCode;
	}

	public void setSupplServiceActionCode(SupplServiceActionCode supplServiceActionCode) {
		this.supplServiceActionCode = supplServiceActionCode;
	}

	public SupplServiceActionCode getSupplServiceActionCode() {
		return supplServiceActionCode;
	}

	public void setSsParameters(SsParameters ssParameters) {
		this.ssParameters = ssParameters;
	}

	public SsParameters getSsParameters() {
		return ssParameters;
	}

	public void setChargingTimeStamp(ChargingTimeStamp chargingTimeStamp) {
		this.chargingTimeStamp = chargingTimeStamp;
	}

	public ChargingTimeStamp getChargingTimeStamp() {
		return chargingTimeStamp;
	}

	public void setChargeInformation(ChargeInformation chargeInformation) {
		this.chargeInformation = chargeInformation;
	}

	public ChargeInformation getChargeInformation() {
		return chargeInformation;
	}

	public void setBasicServiceCodeList(BasicServiceCodeList basicServiceCodeList) {
		this.basicServiceCodeList = basicServiceCodeList;
	}

	public BasicServiceCodeList getBasicServiceCodeList() {
		return basicServiceCodeList;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (basicServiceCodeList != null) {
			codeLength += basicServiceCodeList.encode(reverseOS, true);
		}
		
		if (chargeInformation != null) {
			codeLength += chargeInformation.encode(reverseOS, true);
		}
		
		if (chargingTimeStamp != null) {
			codeLength += chargingTimeStamp.encode(reverseOS, true);
		}
		
		if (ssParameters != null) {
			codeLength += ssParameters.encode(reverseOS, true);
		}
		
		if (supplServiceActionCode != null) {
			codeLength += supplServiceActionCode.encode(reverseOS, true);
		}
		
		if (supplServiceCode != null) {
			codeLength += supplServiceCode.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(SupplServiceCode.tag)) {
			supplServiceCode = new SupplServiceCode();
			vByteCount += supplServiceCode.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(SupplServiceActionCode.tag)) {
			supplServiceActionCode = new SupplServiceActionCode();
			vByteCount += supplServiceActionCode.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(SsParameters.tag)) {
			ssParameters = new SsParameters();
			vByteCount += ssParameters.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ChargingTimeStamp.tag)) {
			chargingTimeStamp = new ChargingTimeStamp();
			vByteCount += chargingTimeStamp.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(ChargeInformation.tag)) {
			chargeInformation = new ChargeInformation();
			vByteCount += chargeInformation.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BasicServiceCodeList.tag)) {
			basicServiceCodeList = new BasicServiceCodeList();
			vByteCount += basicServiceCodeList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (supplServiceCode != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("supplServiceCode: ").append(supplServiceCode);
			firstSelectedElement = false;
		}
		
		if (supplServiceActionCode != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("supplServiceActionCode: ").append(supplServiceActionCode);
			firstSelectedElement = false;
		}
		
		if (ssParameters != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("ssParameters: ").append(ssParameters);
			firstSelectedElement = false;
		}
		
		if (chargingTimeStamp != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargingTimeStamp: ");
			chargingTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (chargeInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargeInformation: ");
			chargeInformation.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (basicServiceCodeList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("basicServiceCodeList: ");
			basicServiceCodeList.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

