/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class TotalAdvisedChargeValue implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 360);

	private byte[] code = null;
	private AdvisedChargeCurrency advisedChargeCurrency = null;
	private TotalAdvisedCharge totalAdvisedCharge = null;
	private TotalAdvisedChargeRefund totalAdvisedChargeRefund = null;
	private TotalCommission totalCommission = null;
	private TotalCommissionRefund totalCommissionRefund = null;
	
	public TotalAdvisedChargeValue() {
	}

	public TotalAdvisedChargeValue(byte[] code) {
		this.code = code;
	}

	public void setAdvisedChargeCurrency(AdvisedChargeCurrency advisedChargeCurrency) {
		this.advisedChargeCurrency = advisedChargeCurrency;
	}

	public AdvisedChargeCurrency getAdvisedChargeCurrency() {
		return advisedChargeCurrency;
	}

	public void setTotalAdvisedCharge(TotalAdvisedCharge totalAdvisedCharge) {
		this.totalAdvisedCharge = totalAdvisedCharge;
	}

	public TotalAdvisedCharge getTotalAdvisedCharge() {
		return totalAdvisedCharge;
	}

	public void setTotalAdvisedChargeRefund(TotalAdvisedChargeRefund totalAdvisedChargeRefund) {
		this.totalAdvisedChargeRefund = totalAdvisedChargeRefund;
	}

	public TotalAdvisedChargeRefund getTotalAdvisedChargeRefund() {
		return totalAdvisedChargeRefund;
	}

	public void setTotalCommission(TotalCommission totalCommission) {
		this.totalCommission = totalCommission;
	}

	public TotalCommission getTotalCommission() {
		return totalCommission;
	}

	public void setTotalCommissionRefund(TotalCommissionRefund totalCommissionRefund) {
		this.totalCommissionRefund = totalCommissionRefund;
	}

	public TotalCommissionRefund getTotalCommissionRefund() {
		return totalCommissionRefund;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (totalCommissionRefund != null) {
			codeLength += totalCommissionRefund.encode(reverseOS, true);
		}
		
		if (totalCommission != null) {
			codeLength += totalCommission.encode(reverseOS, true);
		}
		
		if (totalAdvisedChargeRefund != null) {
			codeLength += totalAdvisedChargeRefund.encode(reverseOS, true);
		}
		
		if (totalAdvisedCharge != null) {
			codeLength += totalAdvisedCharge.encode(reverseOS, true);
		}
		
		if (advisedChargeCurrency != null) {
			codeLength += advisedChargeCurrency.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(AdvisedChargeCurrency.tag)) {
			advisedChargeCurrency = new AdvisedChargeCurrency();
			vByteCount += advisedChargeCurrency.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TotalAdvisedCharge.tag)) {
			totalAdvisedCharge = new TotalAdvisedCharge();
			vByteCount += totalAdvisedCharge.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TotalAdvisedChargeRefund.tag)) {
			totalAdvisedChargeRefund = new TotalAdvisedChargeRefund();
			vByteCount += totalAdvisedChargeRefund.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TotalCommission.tag)) {
			totalCommission = new TotalCommission();
			vByteCount += totalCommission.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TotalCommissionRefund.tag)) {
			totalCommissionRefund = new TotalCommissionRefund();
			vByteCount += totalCommissionRefund.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (advisedChargeCurrency != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("advisedChargeCurrency: ").append(advisedChargeCurrency);
			firstSelectedElement = false;
		}
		
		if (totalAdvisedCharge != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalAdvisedCharge: ").append(totalAdvisedCharge);
			firstSelectedElement = false;
		}
		
		if (totalAdvisedChargeRefund != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalAdvisedChargeRefund: ").append(totalAdvisedChargeRefund);
			firstSelectedElement = false;
		}
		
		if (totalCommission != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalCommission: ").append(totalCommission);
			firstSelectedElement = false;
		}
		
		if (totalCommissionRefund != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalCommissionRefund: ").append(totalCommissionRefund);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

