/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class TrackedCustomerInformation implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 367);

	private byte[] code = null;
	private TrackedCustomerIdList trackedCustomerIdList = null;
	private TrackedCustomerHomeIdList trackedCustomerHomeIdList = null;
	private TrackedCustomerLocList trackedCustomerLocList = null;
	private TrackedCustomerEquipment trackedCustomerEquipment = null;
	
	public TrackedCustomerInformation() {
	}

	public TrackedCustomerInformation(byte[] code) {
		this.code = code;
	}

	public void setTrackedCustomerIdList(TrackedCustomerIdList trackedCustomerIdList) {
		this.trackedCustomerIdList = trackedCustomerIdList;
	}

	public TrackedCustomerIdList getTrackedCustomerIdList() {
		return trackedCustomerIdList;
	}

	public void setTrackedCustomerHomeIdList(TrackedCustomerHomeIdList trackedCustomerHomeIdList) {
		this.trackedCustomerHomeIdList = trackedCustomerHomeIdList;
	}

	public TrackedCustomerHomeIdList getTrackedCustomerHomeIdList() {
		return trackedCustomerHomeIdList;
	}

	public void setTrackedCustomerLocList(TrackedCustomerLocList trackedCustomerLocList) {
		this.trackedCustomerLocList = trackedCustomerLocList;
	}

	public TrackedCustomerLocList getTrackedCustomerLocList() {
		return trackedCustomerLocList;
	}

	public void setTrackedCustomerEquipment(TrackedCustomerEquipment trackedCustomerEquipment) {
		this.trackedCustomerEquipment = trackedCustomerEquipment;
	}

	public TrackedCustomerEquipment getTrackedCustomerEquipment() {
		return trackedCustomerEquipment;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (trackedCustomerEquipment != null) {
			codeLength += trackedCustomerEquipment.encode(reverseOS, true);
		}
		
		if (trackedCustomerLocList != null) {
			codeLength += trackedCustomerLocList.encode(reverseOS, true);
		}
		
		if (trackedCustomerHomeIdList != null) {
			codeLength += trackedCustomerHomeIdList.encode(reverseOS, true);
		}
		
		if (trackedCustomerIdList != null) {
			codeLength += trackedCustomerIdList.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(TrackedCustomerIdList.tag)) {
			trackedCustomerIdList = new TrackedCustomerIdList();
			vByteCount += trackedCustomerIdList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TrackedCustomerHomeIdList.tag)) {
			trackedCustomerHomeIdList = new TrackedCustomerHomeIdList();
			vByteCount += trackedCustomerHomeIdList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TrackedCustomerLocList.tag)) {
			trackedCustomerLocList = new TrackedCustomerLocList();
			vByteCount += trackedCustomerLocList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(TrackedCustomerEquipment.tag)) {
			trackedCustomerEquipment = new TrackedCustomerEquipment();
			vByteCount += trackedCustomerEquipment.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (trackedCustomerIdList != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackedCustomerIdList: ");
			trackedCustomerIdList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (trackedCustomerHomeIdList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackedCustomerHomeIdList: ");
			trackedCustomerHomeIdList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (trackedCustomerLocList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackedCustomerLocList: ");
			trackedCustomerLocList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (trackedCustomerEquipment != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackedCustomerEquipment: ");
			trackedCustomerEquipment.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

