/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class TransferBatch implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 1);

	private byte[] code = null;
	private BatchControlInfo batchControlInfo = null;
	private AccountingInfo accountingInfo = null;
	private NetworkInfo networkInfo = null;
	private MessageDescriptionInfoList messageDescriptionInfo = null;
	private CallEventDetailList callEventDetails = null;
	private AuditControlInfo auditControlInfo = null;
	
	public TransferBatch() {
	}

	public TransferBatch(byte[] code) {
		this.code = code;
	}

	public void setBatchControlInfo(BatchControlInfo batchControlInfo) {
		this.batchControlInfo = batchControlInfo;
	}

	public BatchControlInfo getBatchControlInfo() {
		return batchControlInfo;
	}

	public void setAccountingInfo(AccountingInfo accountingInfo) {
		this.accountingInfo = accountingInfo;
	}

	public AccountingInfo getAccountingInfo() {
		return accountingInfo;
	}

	public void setNetworkInfo(NetworkInfo networkInfo) {
		this.networkInfo = networkInfo;
	}

	public NetworkInfo getNetworkInfo() {
		return networkInfo;
	}

	public void setMessageDescriptionInfo(MessageDescriptionInfoList messageDescriptionInfo) {
		this.messageDescriptionInfo = messageDescriptionInfo;
	}

	public MessageDescriptionInfoList getMessageDescriptionInfo() {
		return messageDescriptionInfo;
	}

	public void setCallEventDetails(CallEventDetailList callEventDetails) {
		this.callEventDetails = callEventDetails;
	}

	public CallEventDetailList getCallEventDetails() {
		return callEventDetails;
	}

	public void setAuditControlInfo(AuditControlInfo auditControlInfo) {
		this.auditControlInfo = auditControlInfo;
	}

	public AuditControlInfo getAuditControlInfo() {
		return auditControlInfo;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (auditControlInfo != null) {
			codeLength += auditControlInfo.encode(reverseOS, true);
		}
		
		if (callEventDetails != null) {
			codeLength += callEventDetails.encode(reverseOS, true);
		}
		
		if (messageDescriptionInfo != null) {
			codeLength += messageDescriptionInfo.encode(reverseOS, true);
		}
		
		if (networkInfo != null) {
			codeLength += networkInfo.encode(reverseOS, true);
		}
		
		if (accountingInfo != null) {
			codeLength += accountingInfo.encode(reverseOS, true);
		}
		
		if (batchControlInfo != null) {
			codeLength += batchControlInfo.encode(reverseOS, true);
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		if (lengthVal == 0) {
			return tlByteCount;
		}
		vByteCount += berTag.decode(is);

		if (berTag.equals(BatchControlInfo.tag)) {
			batchControlInfo = new BatchControlInfo();
			vByteCount += batchControlInfo.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(AccountingInfo.tag)) {
			accountingInfo = new AccountingInfo();
			vByteCount += accountingInfo.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(NetworkInfo.tag)) {
			networkInfo = new NetworkInfo();
			vByteCount += networkInfo.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(MessageDescriptionInfoList.tag)) {
			messageDescriptionInfo = new MessageDescriptionInfoList();
			vByteCount += messageDescriptionInfo.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(CallEventDetailList.tag)) {
			callEventDetails = new CallEventDetailList();
			vByteCount += callEventDetails.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(AuditControlInfo.tag)) {
			auditControlInfo = new AuditControlInfo();
			vByteCount += auditControlInfo.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (batchControlInfo != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("batchControlInfo: ");
			batchControlInfo.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (accountingInfo != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountingInfo: ");
			accountingInfo.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (networkInfo != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("networkInfo: ");
			networkInfo.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (messageDescriptionInfo != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("messageDescriptionInfo: ");
			messageDescriptionInfo.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (callEventDetails != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("callEventDetails: ");
			callEventDetails.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (auditControlInfo != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("auditControlInfo: ");
			auditControlInfo.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

