/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.rap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;

import com.xcess.ocs.tapmodels.tap.AbsoluteAmount;
import com.xcess.ocs.tapmodels.tap.AccountingInfo;
import com.xcess.ocs.tapmodels.tap.AsciiString;
import com.xcess.ocs.tapmodels.tap.AuditControlInfo;
import com.xcess.ocs.tapmodels.tap.BatchControlInfo;
import com.xcess.ocs.tapmodels.tap.CallEventDetail;
import com.xcess.ocs.tapmodels.tap.Code;
import com.xcess.ocs.tapmodels.tap.Currency;
import com.xcess.ocs.tapmodels.tap.DateTimeLong;
import com.xcess.ocs.tapmodels.tap.FileSequenceNumber;
import com.xcess.ocs.tapmodels.tap.FileTypeIndicator;
import com.xcess.ocs.tapmodels.tap.MessageDescription;
import com.xcess.ocs.tapmodels.tap.MessageDescriptionCode;
import com.xcess.ocs.tapmodels.tap.NetworkInfo;
import com.xcess.ocs.tapmodels.tap.Notification;
import com.xcess.ocs.tapmodels.tap.NumberString;
import com.xcess.ocs.tapmodels.tap.OperatorSpecInformation;
import com.xcess.ocs.tapmodels.tap.PlmnId;
import com.xcess.ocs.tapmodels.tap.RapFileSequenceNumber;
import com.xcess.ocs.tapmodels.tap.Recipient;
import com.xcess.ocs.tapmodels.tap.ReleaseVersionNumber;
import com.xcess.ocs.tapmodels.tap.Sender;
import com.xcess.ocs.tapmodels.tap.SpecificationVersionNumber;
import com.xcess.ocs.tapmodels.tap.TapCurrency;
import com.xcess.ocs.tapmodels.tap.TapDecimalPlaces;

public class FatalReturn implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 539);

	private byte[] code = null;
	private FileSequenceNumber fileSequenceNumber = null;
	private TransferBatchError transferBatchError = null;
	private NotificationError notificationError = null;
	private BatchControlError batchControlError = null;
	private AccountingInfoError accountingInfoError = null;
	private NetworkInfoError networkInfoError = null;
	private MessageDescriptionError messageDescriptionError = null;
	private AuditControlInfoError auditControlInfoError = null;
	private OperatorSpecList operatorSpecList = null;
	
	public FatalReturn() {
	}

	public FatalReturn(byte[] code) {
		this.code = code;
	}

	public void setFileSequenceNumber(FileSequenceNumber fileSequenceNumber) {
		this.fileSequenceNumber = fileSequenceNumber;
	}

	public FileSequenceNumber getFileSequenceNumber() {
		return fileSequenceNumber;
	}

	public void setTransferBatchError(TransferBatchError transferBatchError) {
		this.transferBatchError = transferBatchError;
	}

	public TransferBatchError getTransferBatchError() {
		return transferBatchError;
	}

	public void setNotificationError(NotificationError notificationError) {
		this.notificationError = notificationError;
	}

	public NotificationError getNotificationError() {
		return notificationError;
	}

	public void setBatchControlError(BatchControlError batchControlError) {
		this.batchControlError = batchControlError;
	}

	public BatchControlError getBatchControlError() {
		return batchControlError;
	}

	public void setAccountingInfoError(AccountingInfoError accountingInfoError) {
		this.accountingInfoError = accountingInfoError;
	}

	public AccountingInfoError getAccountingInfoError() {
		return accountingInfoError;
	}

	public void setNetworkInfoError(NetworkInfoError networkInfoError) {
		this.networkInfoError = networkInfoError;
	}

	public NetworkInfoError getNetworkInfoError() {
		return networkInfoError;
	}

	public void setMessageDescriptionError(MessageDescriptionError messageDescriptionError) {
		this.messageDescriptionError = messageDescriptionError;
	}

	public MessageDescriptionError getMessageDescriptionError() {
		return messageDescriptionError;
	}

	public void setAuditControlInfoError(AuditControlInfoError auditControlInfoError) {
		this.auditControlInfoError = auditControlInfoError;
	}

	public AuditControlInfoError getAuditControlInfoError() {
		return auditControlInfoError;
	}

	public void setOperatorSpecList(OperatorSpecList operatorSpecList) {
		this.operatorSpecList = operatorSpecList;
	}

	public OperatorSpecList getOperatorSpecList() {
		return operatorSpecList;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (operatorSpecList != null) {
			codeLength += operatorSpecList.encode(reverseOS, true);
		}
		
		if (auditControlInfoError != null) {
			codeLength += auditControlInfoError.encode(reverseOS, true);
		}
		
		if (messageDescriptionError != null) {
			codeLength += messageDescriptionError.encode(reverseOS, true);
		}
		
		if (networkInfoError != null) {
			codeLength += networkInfoError.encode(reverseOS, true);
		}
		
		if (accountingInfoError != null) {
			codeLength += accountingInfoError.encode(reverseOS, true);
		}
		
		if (batchControlError != null) {
			codeLength += batchControlError.encode(reverseOS, true);
		}
		
		if (notificationError != null) {
			codeLength += notificationError.encode(reverseOS, true);
		}
		
		if (transferBatchError != null) {
			codeLength += transferBatchError.encode(reverseOS, true);
		}
		
		codeLength += fileSequenceNumber.encode(reverseOS, true);
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		vByteCount += berTag.decode(is);

		if (berTag.equals(FileSequenceNumber.tag)) {
			fileSequenceNumber = new FileSequenceNumber();
			vByteCount += fileSequenceNumber.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match mandatory sequence component.");
		}
		
		if (berTag.equals(TransferBatchError.tag)) {
			transferBatchError = new TransferBatchError();
			vByteCount += transferBatchError.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(NotificationError.tag)) {
			notificationError = new NotificationError();
			vByteCount += notificationError.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BatchControlError.tag)) {
			batchControlError = new BatchControlError();
			vByteCount += batchControlError.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(AccountingInfoError.tag)) {
			accountingInfoError = new AccountingInfoError();
			vByteCount += accountingInfoError.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(NetworkInfoError.tag)) {
			networkInfoError = new NetworkInfoError();
			vByteCount += networkInfoError.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(MessageDescriptionError.tag)) {
			messageDescriptionError = new MessageDescriptionError();
			vByteCount += messageDescriptionError.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(AuditControlInfoError.tag)) {
			auditControlInfoError = new AuditControlInfoError();
			vByteCount += auditControlInfoError.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(OperatorSpecList.tag)) {
			operatorSpecList = new OperatorSpecList();
			vByteCount += operatorSpecList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		sb.append("\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (fileSequenceNumber != null) {
			sb.append("fileSequenceNumber: ").append(fileSequenceNumber);
		}
		else {
			sb.append("fileSequenceNumber: <empty-required-field>");
		}
		
		if (transferBatchError != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("transferBatchError: ");
			transferBatchError.appendAsString(sb, indentLevel + 1);
		}
		
		if (notificationError != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("notificationError: ");
			notificationError.appendAsString(sb, indentLevel + 1);
		}
		
		if (batchControlError != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("batchControlError: ");
			batchControlError.appendAsString(sb, indentLevel + 1);
		}
		
		if (accountingInfoError != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountingInfoError: ");
			accountingInfoError.appendAsString(sb, indentLevel + 1);
		}
		
		if (networkInfoError != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("networkInfoError: ");
			networkInfoError.appendAsString(sb, indentLevel + 1);
		}
		
		if (messageDescriptionError != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("messageDescriptionError: ");
			messageDescriptionError.appendAsString(sb, indentLevel + 1);
		}
		
		if (auditControlInfoError != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("auditControlInfoError: ");
			auditControlInfoError.appendAsString(sb, indentLevel + 1);
		}
		
		if (operatorSpecList != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("operatorSpecList: ");
			operatorSpecList.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

