/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.rap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;

import com.xcess.ocs.tapmodels.tap.AbsoluteAmount;
import com.xcess.ocs.tapmodels.tap.AccountingInfo;
import com.xcess.ocs.tapmodels.tap.AsciiString;
import com.xcess.ocs.tapmodels.tap.AuditControlInfo;
import com.xcess.ocs.tapmodels.tap.BatchControlInfo;
import com.xcess.ocs.tapmodels.tap.CallEventDetail;
import com.xcess.ocs.tapmodels.tap.Code;
import com.xcess.ocs.tapmodels.tap.Currency;
import com.xcess.ocs.tapmodels.tap.DateTimeLong;
import com.xcess.ocs.tapmodels.tap.FileSequenceNumber;
import com.xcess.ocs.tapmodels.tap.FileTypeIndicator;
import com.xcess.ocs.tapmodels.tap.MessageDescription;
import com.xcess.ocs.tapmodels.tap.MessageDescriptionCode;
import com.xcess.ocs.tapmodels.tap.NetworkInfo;
import com.xcess.ocs.tapmodels.tap.Notification;
import com.xcess.ocs.tapmodels.tap.NumberString;
import com.xcess.ocs.tapmodels.tap.OperatorSpecInformation;
import com.xcess.ocs.tapmodels.tap.PlmnId;
import com.xcess.ocs.tapmodels.tap.RapFileSequenceNumber;
import com.xcess.ocs.tapmodels.tap.Recipient;
import com.xcess.ocs.tapmodels.tap.ReleaseVersionNumber;
import com.xcess.ocs.tapmodels.tap.Sender;
import com.xcess.ocs.tapmodels.tap.SpecificationVersionNumber;
import com.xcess.ocs.tapmodels.tap.TapCurrency;
import com.xcess.ocs.tapmodels.tap.TapDecimalPlaces;

public class RapDataInterChange implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	private byte[] code = null;
	private ReturnBatch returnBatch = null;
	private Acknowledgement acknowledgement = null;
	
	public RapDataInterChange() {
	}

	public RapDataInterChange(byte[] code) {
		this.code = code;
	}

	public void setReturnBatch(ReturnBatch returnBatch) {
		this.returnBatch = returnBatch;
	}

	public ReturnBatch getReturnBatch() {
		return returnBatch;
	}

	public void setAcknowledgement(Acknowledgement acknowledgement) {
		this.acknowledgement = acknowledgement;
	}

	public Acknowledgement getAcknowledgement() {
		return acknowledgement;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			return code.length;
		}

		int codeLength = 0;
		if (acknowledgement != null) {
			codeLength += acknowledgement.encode(reverseOS, true);
			return codeLength;
		}
		
		if (returnBatch != null) {
			codeLength += returnBatch.encode(reverseOS, true);
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int tlvByteCount = 0;
		boolean tagWasPassed = (berTag != null);

		if (berTag == null) {
			berTag = new BerTag();
			tlvByteCount += berTag.decode(is);
		}

		if (berTag.equals(ReturnBatch.tag)) {
			returnBatch = new ReturnBatch();
			tlvByteCount += returnBatch.decode(is, false);
			return tlvByteCount;
		}

		if (berTag.equals(Acknowledgement.tag)) {
			acknowledgement = new Acknowledgement();
			tlvByteCount += acknowledgement.decode(is, false);
			return tlvByteCount;
		}

		if (tagWasPassed) {
			return 0;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (returnBatch != null) {
			sb.append("returnBatch: ");
			returnBatch.appendAsString(sb, indentLevel + 1);
			return;
		}

		if (acknowledgement != null) {
			sb.append("acknowledgement: ");
			acknowledgement.appendAsString(sb, indentLevel + 1);
			return;
		}

		sb.append("<none>");
	}

}

