/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.rap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;

import com.xcess.ocs.tapmodels.tap.AbsoluteAmount;
import com.xcess.ocs.tapmodels.tap.AccountingInfo;
import com.xcess.ocs.tapmodels.tap.AsciiString;
import com.xcess.ocs.tapmodels.tap.AuditControlInfo;
import com.xcess.ocs.tapmodels.tap.BatchControlInfo;
import com.xcess.ocs.tapmodels.tap.CallEventDetail;
import com.xcess.ocs.tapmodels.tap.Code;
import com.xcess.ocs.tapmodels.tap.Currency;
import com.xcess.ocs.tapmodels.tap.DateTimeLong;
import com.xcess.ocs.tapmodels.tap.FileSequenceNumber;
import com.xcess.ocs.tapmodels.tap.FileTypeIndicator;
import com.xcess.ocs.tapmodels.tap.MessageDescription;
import com.xcess.ocs.tapmodels.tap.MessageDescriptionCode;
import com.xcess.ocs.tapmodels.tap.NetworkInfo;
import com.xcess.ocs.tapmodels.tap.Notification;
import com.xcess.ocs.tapmodels.tap.NumberString;
import com.xcess.ocs.tapmodels.tap.OperatorSpecInformation;
import com.xcess.ocs.tapmodels.tap.PlmnId;
import com.xcess.ocs.tapmodels.tap.RapFileSequenceNumber;
import com.xcess.ocs.tapmodels.tap.Recipient;
import com.xcess.ocs.tapmodels.tap.ReleaseVersionNumber;
import com.xcess.ocs.tapmodels.tap.Sender;
import com.xcess.ocs.tapmodels.tap.SpecificationVersionNumber;
import com.xcess.ocs.tapmodels.tap.TapCurrency;
import com.xcess.ocs.tapmodels.tap.TapDecimalPlaces;

public class ReturnDetail implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	private byte[] code = null;
	private StopReturn stopReturn = null;
	private MissingReturn missingReturn = null;
	private FatalReturn fatalReturn = null;
	private SevereReturn severeReturn = null;
	
	public ReturnDetail() {
	}

	public ReturnDetail(byte[] code) {
		this.code = code;
	}

	public void setStopReturn(StopReturn stopReturn) {
		this.stopReturn = stopReturn;
	}

	public StopReturn getStopReturn() {
		return stopReturn;
	}

	public void setMissingReturn(MissingReturn missingReturn) {
		this.missingReturn = missingReturn;
	}

	public MissingReturn getMissingReturn() {
		return missingReturn;
	}

	public void setFatalReturn(FatalReturn fatalReturn) {
		this.fatalReturn = fatalReturn;
	}

	public FatalReturn getFatalReturn() {
		return fatalReturn;
	}

	public void setSevereReturn(SevereReturn severeReturn) {
		this.severeReturn = severeReturn;
	}

	public SevereReturn getSevereReturn() {
		return severeReturn;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			return code.length;
		}

		int codeLength = 0;
		if (severeReturn != null) {
			codeLength += severeReturn.encode(reverseOS, true);
			return codeLength;
		}
		
		if (fatalReturn != null) {
			codeLength += fatalReturn.encode(reverseOS, true);
			return codeLength;
		}
		
		if (missingReturn != null) {
			codeLength += missingReturn.encode(reverseOS, true);
			return codeLength;
		}
		
		if (stopReturn != null) {
			codeLength += stopReturn.encode(reverseOS, true);
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int tlvByteCount = 0;
		boolean tagWasPassed = (berTag != null);

		if (berTag == null) {
			berTag = new BerTag();
			tlvByteCount += berTag.decode(is);
		}

		if (berTag.equals(StopReturn.tag)) {
			stopReturn = new StopReturn();
			tlvByteCount += stopReturn.decode(is, false);
			return tlvByteCount;
		}

		if (berTag.equals(MissingReturn.tag)) {
			missingReturn = new MissingReturn();
			tlvByteCount += missingReturn.decode(is, false);
			return tlvByteCount;
		}

		if (berTag.equals(FatalReturn.tag)) {
			fatalReturn = new FatalReturn();
			tlvByteCount += fatalReturn.decode(is, false);
			return tlvByteCount;
		}

		if (berTag.equals(SevereReturn.tag)) {
			severeReturn = new SevereReturn();
			tlvByteCount += severeReturn.decode(is, false);
			return tlvByteCount;
		}

		if (tagWasPassed) {
			return 0;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (stopReturn != null) {
			sb.append("stopReturn: ");
			stopReturn.appendAsString(sb, indentLevel + 1);
			return;
		}

		if (missingReturn != null) {
			sb.append("missingReturn: ");
			missingReturn.appendAsString(sb, indentLevel + 1);
			return;
		}

		if (fatalReturn != null) {
			sb.append("fatalReturn: ");
			fatalReturn.appendAsString(sb, indentLevel + 1);
			return;
		}

		if (severeReturn != null) {
			sb.append("severeReturn: ");
			severeReturn.appendAsString(sb, indentLevel + 1);
			return;
		}

		sb.append("<none>");
	}

}

