/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package com.xcess.ocs.tapmodels.rap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;

import com.xcess.ocs.tapmodels.tap.AbsoluteAmount;
import com.xcess.ocs.tapmodels.tap.AccountingInfo;
import com.xcess.ocs.tapmodels.tap.AsciiString;
import com.xcess.ocs.tapmodels.tap.AuditControlInfo;
import com.xcess.ocs.tapmodels.tap.BatchControlInfo;
import com.xcess.ocs.tapmodels.tap.CallEventDetail;
import com.xcess.ocs.tapmodels.tap.Code;
import com.xcess.ocs.tapmodels.tap.Currency;
import com.xcess.ocs.tapmodels.tap.DateTimeLong;
import com.xcess.ocs.tapmodels.tap.FileSequenceNumber;
import com.xcess.ocs.tapmodels.tap.FileTypeIndicator;
import com.xcess.ocs.tapmodels.tap.MessageDescription;
import com.xcess.ocs.tapmodels.tap.MessageDescriptionCode;
import com.xcess.ocs.tapmodels.tap.NetworkInfo;
import com.xcess.ocs.tapmodels.tap.Notification;
import com.xcess.ocs.tapmodels.tap.NumberString;
import com.xcess.ocs.tapmodels.tap.OperatorSpecInformation;
import com.xcess.ocs.tapmodels.tap.PlmnId;
import com.xcess.ocs.tapmodels.tap.RapFileSequenceNumber;
import com.xcess.ocs.tapmodels.tap.Recipient;
import com.xcess.ocs.tapmodels.tap.ReleaseVersionNumber;
import com.xcess.ocs.tapmodels.tap.Sender;
import com.xcess.ocs.tapmodels.tap.SpecificationVersionNumber;
import com.xcess.ocs.tapmodels.tap.TapCurrency;
import com.xcess.ocs.tapmodels.tap.TapDecimalPlaces;

public class StopReturn implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 554);

	private byte[] code = null;
	private LastSeqNumber lastSeqNumber = null;
	private OperatorSpecList operatorSpecList = null;
	
	public StopReturn() {
	}

	public StopReturn(byte[] code) {
		this.code = code;
	}

	public void setLastSeqNumber(LastSeqNumber lastSeqNumber) {
		this.lastSeqNumber = lastSeqNumber;
	}

	public LastSeqNumber getLastSeqNumber() {
		return lastSeqNumber;
	}

	public void setOperatorSpecList(OperatorSpecList operatorSpecList) {
		this.operatorSpecList = operatorSpecList;
	}

	public OperatorSpecList getOperatorSpecList() {
		return operatorSpecList;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (operatorSpecList != null) {
			codeLength += operatorSpecList.encode(reverseOS, true);
		}
		
		codeLength += lastSeqNumber.encode(reverseOS, true);
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		vByteCount += berTag.decode(is);

		if (berTag.equals(LastSeqNumber.tag)) {
			lastSeqNumber = new LastSeqNumber();
			vByteCount += lastSeqNumber.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match mandatory sequence component.");
		}
		
		if (berTag.equals(OperatorSpecList.tag)) {
			operatorSpecList = new OperatorSpecList();
			vByteCount += operatorSpecList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		sb.append("\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (lastSeqNumber != null) {
			sb.append("lastSeqNumber: ").append(lastSeqNumber);
		}
		else {
			sb.append("lastSeqNumber: <empty-required-field>");
		}
		
		if (operatorSpecList != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("operatorSpecList: ");
			operatorSpecList.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

